-- Tracking				Date			Name	Description
-- CBCAXUPISSLOG-688	29-JUN-2021		NY		Initial config from UAT environment
-- CBCAXUPISSLOG-663	29-JUN-2021		WY		Change terminal number to 9999 and bank mnem refers to acquiring bank name for issuing tran
-- CBCAXUPISSLOG-688	30-JUN-2021		NY		Update query following excel spec
-- CBCAXUPISSLOG-688	30-JUN-2021		NY		Adding back tsc code 41, populate 0 count for short dispense
-- CBCAXUPISSLOG-688	01-JUL-2021		NY		Fix redundant row, catch inter-entity txn accordingly
-- CBCAXUPISSLOG-688	05-JUL-2021		NY		Fix recycler txn not showing on verification
-- CBCAXUPISSLOG-765	05-JUL-2021		NY		Fix wrong acquirer/issuer records
-- CBCAXUPISSLOG-766	07-JUL-2021		NY		Exclude IBFT/Eload request ie 44/52 from acquirer/onus report, include IBFT withdrawal 01
-- CBCAXUPISSLOG-546	07-JUL-2021		NY		Correct tran mnem for IBFT withdrawal BTD/BTR
-- CBCAXUPISSLOG-766	10-JUL-2021		NY		Fix fund transfer has duplicate entries ie AXD/AXC AID/AIC
-- CBCAXUPISSLOG-768	10-JUL-2021		NY		Fix beep txn has no amount populated
-- CBCAXUPISSLOG-767	10-JUL-2021		NY		Fix reversal count into correct column
-- CBCAXUPISSLOG-766	12-JUL-2021		NY		Fix missing acquirer txn in report
-- CBCAXUPISSLOG-803	14-JUL-2021  	NY		Issuer credit transaction for other bank card at other bank atm should not include in master list
-- CBCAXUPISSLOG-766	14-JUL-2021		NY 		Fix 44 tran code mnem not printed
-- CBCAXUPISSLOG-773	27-JUL-2021		NY		Get onus cheque book amount from TRL_ISS_CHARGE_AMT
-- Master report		30-JUL-2021		NY		Work on various jira related to master report
-- CBCAXUPISSLOG-767	31-JUL-2021		NY		Fix reversal total sum to be 0, fix along instapay txn appear in individual report show wrong count in master report 
-- Master report		31-JUL-2021		NY		Fix RFID records print individual report not in master reports
-- Master report		01-AUG-2021		NY		Fix eload withdrawal not populate BPR/BRP, transaction code 44 is retrieved instead of 01/41 from BN only for IBFT
-- Master report		02-AUG-2021		NY		Fix Bill Payment wrong mnem/count, along with empty mnem in master reports
-- Master report		02-AUG-2021		NY		Use left join to cbc_bin/cbc_bank so that we still pull data with no bin
-- Master report		06-AUG-2021		NY		Various fix from cross checking finding and jira related issues
-- CBCAXUPISSLOG-854	07-AUG-2021		NY		Exclude reversal count if it is reject reversal
-- Master report		10-AUG-2021		NY		Cater cash card fund transfer debit leg from EBK/MBK
-- Master report		13-AUG-2021		NY		onus/acq ibft/eload to use 44/52 instead of 01 for catching the debit leg
-- Master report		15-AUG-2021		NY		Fix some transfer not accumulate amount accordingly in EFDLY003/TRAN
-- Master report		15-AUG-2021		NY		Fix acquiring prepaid reload printing APR, instead of BPR
-- Master report		17-AUG-2021		NY		Fix wrong RFID decline count
-- Master report		20-AUG-2021		NY		Include back txn code 2, 22
-- Master report		23-AUG-2021		NY		Cater credit leg for txn code 44 and 48
-- CBCAXUPISSLOG-767	23-AUG-2021		NY		Add "-" sign to reversed amount in TRAN
-- Master report		24-AUG-2021		NY		Fix missing txn code 43
-- CBCAXUPISSLOG-851	25-AUG-2021		NY		POS txn sum amount to display under payment column
-- CBCAXUPISSLOG-769	25-AUG-2021		NY		Differentiate MAA/EAA for txn code 126
-- CBCAXUPISSLOG-769	27-AUG-2021		NY		Join atm_txn_activity log to trl_ext_id instead of trl_id

DECLARE
	i_HEADER_FIELDS CLOB;
    i_BODY_FIELDS CLOB;
    i_TRAILER_FIELDS CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;
BEGIN 

-- Transaction Count Report
	i_HEADER_FIELDS := TO_CLOB('[]');
	i_BODY_FIELDS := TO_CLOB('[{"sequence":1,"sectionName":"1","fieldName":"DATE","csvTxtLength":"8","fieldType":"Date","defaultValue":"","firstField":true,"bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"fieldFormat":"MM/dd/yy"},{"sequence":2,"sectionName":"2","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","defaultValue":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":3,"sectionName":"3","fieldName":"TERMINAL","csvTxtLength":"4","fieldType":"String","bodyHeader":false,"defaultValue":"","leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":4,"sectionName":"4","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","defaultValue":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":5,"sectionName":"5","fieldName":"BANK MNEM","csvTxtLength":"3","fieldType":"String","defaultValue":"","fieldFormat":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":6,"sectionName":"6","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","fieldFormat":"","bodyHeader":false,"defaultValue":"","leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":7,"sectionName":"7","fieldName":"TRAN MNEM","csvTxtLength":"3","fieldType":"String","defaultValue":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"tagValue":null},{"sequence":8,"sectionName":"8","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","defaultValue":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"tagValue":null},{"sequence":9,"sectionName":"32","fieldName":"BILLER MNEM","csvTxtLength":"4","pdfLength":"","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":10,"sectionName":"33","fieldName":"SPACE","csvTxtLength":"2","pdfLength":"","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":11,"sectionName":"11","fieldName":"APPROVED TRAN COUNT","csvTxtLength":"11","fieldType":"Number","defaultValue":"","bodyHeader":false,"leftJustified":false,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"fieldFormat":","},{"sequence":12,"sectionName":"12","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","bodyHeader":false,"defaultValue":"","leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":13,"sectionName":"13","fieldName":"REJECTED TRAN COUNT","csvTxtLength":"11","fieldType":"Number","bodyHeader":false,"defaultValue":"","leftJustified":false,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"fieldFormat":","},{"sequence":14,"sectionName":"14","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","defaultValue":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false,"decryptionKey":null},{"sequence":15,"sectionName":"15","fieldName":"TOTAL TRAN COUNT","csvTxtLength":"14","fieldType":"Number","eol":false,"leftJustified":false,"padFieldLength":0,"decrypt":false,"decryptionKey":null,"fieldFormat":","},{"sequence":16,"sectionName":"16","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","delimiter":"","fieldFormat":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":17,"sectionName":"17","fieldName":"SHORT DISPENSE COUNT","csvTxtLength":"11","fieldType":"Number","delimiter":"","fieldFormat":",","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":18,"sectionName":"18","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":19,"sectionName":"19","fieldName":"NO DISPENSE COUNT","csvTxtLength":"11","fieldType":"Number","delimiter":"","fieldFormat":",","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":20,"sectionName":"20","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","delimiter":"","fieldFormat":"","bodyHeader":false,"leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":21,"sectionName":"21","fieldName":"OVER DISPENSE COUNT","csvTxtLength":"11","fieldType":"Number","delimiter":"","fieldFormat":",","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":22,"sectionName":"22","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":23,"sectionName":"23","fieldName":"HARDWARE FAILURE COUNT","csvTxtLength":"11","fieldType":"Number","delimiter":"","fieldFormat":",","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":24,"sectionName":"24","fieldName":"SPACE","csvTxtLength":"2","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":25,"sectionName":"25","fieldName":"CASH DISPENSED","csvTxtLength":"16","fieldType":"Decimal","delimiter":"","fieldFormat":"#,##0.00","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":26,"sectionName":"32","fieldName":"REVERSAL SIGN CD","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":27,"sectionName":"26","fieldName":"SPACE","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":28,"sectionName":"27","fieldName":"DEPOSITS","csvTxtLength":"17","fieldType":"Decimal","delimiter":"","fieldFormat":"#,##0.00","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":29,"sectionName":"33","fieldName":"REVERSAL SIGN DP","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":30,"sectionName":"28","fieldName":"SPACE","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":31,"sectionName":"29","fieldName":"BILL PAYMENTS","csvTxtLength":"17","fieldType":"Decimal","delimiter":"","fieldFormat":"#,##0.00","leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":32,"sectionName":"34","fieldName":"REVERSAL SIGN BP","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":33,"sectionName":"30","fieldName":"SPACE","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false},{"sequence":34,"sectionName":"31","fieldName":"TRANSFERS","csvTxtLength":"17","fieldType":"Decimal","delimiter":"","fieldFormat":"#,##0.00","eol":false,"leftJustified":false,"padFieldLength":0,"decrypt":false},{"sequence":35,"sectionName":"35","fieldName":"REVERSAL SIGN TRFR","csvTxtLength":"1","fieldType":"String","delimiter":"","fieldFormat":"","leftJustified":true,"padFieldLength":0,"decrypt":false,"eol":true}]');
	i_TRAILER_FIELDS := TO_CLOB('[]');
	i_BODY_QUERY := TO_CLOB('		
SELECT
      "TXN QUALIFIER",
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
	  "BILLER MNEM",
      "BANK CODE",
      SUM("APPROVED TRAN COUNT") "APPROVED TRAN COUNT",
      SUM("REJECTED TRAN COUNT") "REJECTED TRAN COUNT",
      SUM("TOTAL TRAN COUNT") "TOTAL TRAN COUNT",
      0 "SHORT DISPENSE COUNT",
      SUM("NO DISP") "NO DISPENSE COUNT",
      SUM("OVER DISPENSE") "OVER DISPENSE COUNT",
      0 "HARDWARE FAILURE COUNT",
      SUM("CASH DISPENSED") "CASH DISPENSED",
      ''-'' "REVERSAL SIGN CD",
      SUM("DEPOSITS") "DEPOSITS",
      ''-'' "REVERSAL SIGN DP",
      SUM("BILL PAYMENTS") "BILL PAYMENTS",
      ''-'' "REVERSAL SIGN BP",
      SUM("TRANSFERS") "TRANSFERS",
      ''-'' "REVERSAL SIGN TRFR"
FROM (
-- Onus (exclude Transfer)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) AS "TERMINAL",
      CASE WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXN.TRL_TSC_CODE = 90 THEN ''PIN'' 
		WHEN TXN.TRL_TSC_CODE = 126 AND ATA.ATA_TXN_TYPE LIKE ''EBK%'' THEN ''EAA'' 
        WHEN TXN.TRL_TSC_CODE = 126 AND ATA.ATA_TXN_TYPE LIKE ''MBK%'' THEN ''MAA''  
		WHEN TXN.TRL_TSC_CODE = 129 THEN ''LST'' 
        WHEN TXN.TRL_TSC_CODE = 131 THEN ''FPC''
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE 
        WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE = 122 THEN TXN.TRL_ISS_CHARGE_AMT
   		WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 52) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) = CTR.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
      LEFT JOIN ATM_TXN_ACTIVITY_LOG ATA ON ATA.ATA_TRL_ID = TXN.TRL_EXT_ID
WHERE
	  (TXN.TRL_TQU_ID IN (''F'', ''R'') OR (TXN.TRL_TQU_ID = ''A'' AND (TRL_TSC_CODE IN (90, 129, 131, 142, 143) OR TRL_TSC_CODE = 126 AND ATA.ATA_TXN_TYPE IN (''EBK Pin Registration'', ''MBK Pin Registration''))))
      AND TXN.TRL_FRD_REV_INST_ID IS NULL 
      AND TXN.TRL_CARD_ACPT_TERMINAL_IDENT != 12345
      AND TXN.TRL_TSC_CODE NOT IN (42, 44, 45, 46, 47, 48, 49, 52, 252)
      AND COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_Iss_Name} 
	  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Onus Transfer (debit)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) AS "TERMINAL",
      CASE WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXN.TRL_TSC_CODE IN (48, 49) AND TXN.TRL_TQU_ID = ''R'' THEN CTRD.CTR_REV_MNEM
        WHEN TXN.TRL_TSC_CODE IN (48, 49) AND TXN.TRL_TQU_ID = ''F'' THEN CTRD.CTR_MNEM
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) AND CTR.CTR_CODE NOT IN (48, 49) AND CTR.CTR_DEBIT_CREDIT IN (''DEBIT'', ''CREDIT'')
      LEFT JOIN CBC_TRAN_CODE CTRD ON TXN.TRL_TSC_CODE = CTRD.CTR_CODE AND CTRD.CTR_CHANNEL = (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) AND CTRD.CTR_CODE IN (48, 49) AND CTRD.CTR_DEBIT_CREDIT = ''DEBIT''
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'')
      AND TXN.TRL_FRD_REV_INST_ID IS NOT NULL
      AND TXN.TRL_TSC_CODE IN (42, 43, 44, 45, 46, 47, 48, 49, 51, 52)
      AND COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_Iss_Name} 
	  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Acquirer (exclude Transfer)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN ''9999''			
		ELSE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) END AS "TERMINAL",
      CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN CBA_ACQ.CBA_MNEM
		WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM  
	    WHEN TXN.TRL_TQU_ID = ''R'' AND (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'') IS NOT NULL
			THEN (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'')
		WHEN TXN.TRL_TQU_ID = ''F'' AND (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'') IS NOT NULL
			THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'')
	    WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) = CTR.CTR_CHANNEL
	  LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''I-CDM'' ELSE ''I-'' || TXNC.TRL_ORIGIN_CHANNEL END) = CTRI.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_FRD_REV_INST_ID IS NULL 
      AND TXN.TRL_TSC_CODE NOT IN (40, 42, 44, 45, 46, 47, 48, 49, 52, 252)
      AND TXN.TRL_CARD_ACPT_TERMINAL_IDENT != 12345
      AND (TXN.TRL_ISS_NAME IS NULL OR COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_IE_Iss_Name})
	  AND (CBA.CBA_MNEM IS NULL OR CBA.CBA_MNEM != {V_Iss_Name})
	  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Acquirer Transfer (debit)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN ''9999''			
		ELSE 
			SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) END AS "TERMINAL",
      CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN CBA_ACQ.CBA_MNEM
		WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM 
        WHEN TXN.TRL_TQU_ID = ''R'' AND (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'') IS NOT NULL
			THEN (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'')
		WHEN TXN.TRL_TQU_ID = ''F'' AND (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'') IS NOT NULL
			THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''DEBIT'') 
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID      
	  LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) = CTR.CTR_CHANNEL
	  LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''I-CDM'' ELSE ''I-'' || TXNC.TRL_ORIGIN_CHANNEL END) = CTRI.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_FRD_REV_INST_ID IS NOT NULL 
      AND TXN.TRL_TSC_CODE IN (40, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 252)
      AND CTR.CTR_DEBIT_CREDIT = ''DEBIT''
      AND CTRI.CTR_DEBIT_CREDIT = ''DEBIT''
      AND (TXN.TRL_ISS_NAME IS NULL OR COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_IE_Iss_Name})
	  AND (CBA.CBA_MNEM IS NULL OR CBA.CBA_MNEM != {V_Iss_Name})
	  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Acquirer Transfer (credit)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN ''9999''			
		ELSE 
			SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) END AS "TERMINAL",
      CASE 
		WHEN LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id} THEN CBA_ACQ.CBA_MNEM
		WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM 
        WHEN TXN.TRL_TQU_ID = ''R'' AND (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''CREDIT'') IS NOT NULL
			THEN (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''CREDIT'')
		WHEN TXN.TRL_TQU_ID = ''F'' AND (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''CREDIT'') IS NOT NULL
			THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT = ''CREDIT'') 
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID      
	  LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''CDM'' ELSE TXNC.TRL_ORIGIN_CHANNEL END) = CTR.CTR_CHANNEL 
	  LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND (CASE WHEN TXNC.TRL_ORIGIN_CHANNEL = ''BRM'' THEN ''I-CDM'' ELSE ''I-'' || TXNC.TRL_ORIGIN_CHANNEL END) = CTRI.CTR_CHANNEL 
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_FRD_REV_INST_ID IS NOT NULL 
      AND TXN.TRL_TSC_CODE IN (44, 48)
      AND CTR.CTR_DEBIT_CREDIT = ''CREDIT''
      AND CTRI.CTR_DEBIT_CREDIT = ''CREDIT''
      AND (TXN.TRL_ISS_NAME IS NULL OR COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_IE_Iss_Name})
	  AND (CBA.CBA_MNEM IS NULL OR CBA.CBA_MNEM != {V_Iss_Name})
	  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
      AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_Recv_Inst_Id}
      AND {Txn_Date}
UNION ALL
-- Issuer (exclude Transfer)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  ''9999'' AS "TERMINAL",
      CASE WHEN CBA_ACQ.CBA_MNEM IS NOT NULL THEN CBA_ACQ.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM  
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''BNT''
	  LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND ''I-'' || TXNC.TRL_ORIGIN_CHANNEL = CTRI.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_FRD_REV_INST_ID IS NULL 
      AND TXN.TRL_TSC_CODE NOT IN (2, 22)
      AND TXN.TRL_CARD_ACPT_TERMINAL_IDENT != 12345
      AND COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_Iss_Name} 
	  AND (TXN.TRL_DEO_NAME != {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Issuer Transfer (debit)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  ''9999'' AS "TERMINAL",
      CASE WHEN CBA_ACQ.CBA_MNEM IS NOT NULL THEN CBA_ACQ.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE
        WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM  
        WHEN TXN.TRL_TQU_ID = ''R'' AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = ''0000008882'' AND TXN.TRL_TSC_CODE = 1 THEN ''BRP''
        WHEN TXN.TRL_TQU_ID = ''F'' AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = ''0000008882'' AND TXN.TRL_TSC_CODE = 1 THEN ''BPR''  
        WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_TSC_CODE = 1 THEN ''BTR''
        WHEN TXN.TRL_TQU_ID = ''F'' AND TXN.TRL_TSC_CODE = 1 THEN ''BTD''
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''BNT''
      LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND ''I-'' || TXNC.TRL_ORIGIN_CHANNEL = CTRI.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_TSC_CODE NOT IN (44, 52)
      AND TXN.TRL_FRD_REV_INST_ID IS NOT NULL
      AND CTR.CTR_DEBIT_CREDIT = ''DEBIT''
      AND COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_Iss_Name} 
	  AND (TXN.TRL_DEO_NAME != {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id})
      AND {Txn_Date}
UNION ALL
-- Issuer Transfer (credit)
SELECT DISTINCT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''yyyy-mm-dd'') "DATE", 
	  ''9999'' AS "TERMINAL",
      CASE WHEN CBA_ACQ.CBA_MNEM IS NOT NULL THEN CBA_ACQ.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''R'' AND CTRI.CTR_REV_MNEM IS NOT NULL THEN CTRI.CTR_REV_MNEM 
		WHEN TXNC.TRL_IS_INTER_ENTITY = 1 AND TXN.TRL_TQU_ID = ''F'' AND CTRI.CTR_MNEM IS NOT NULL THEN CTRI.CTR_MNEM  
		WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
	  CBL.CBL_MNEM AS "BILLER MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE > 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      CASE WHEN TXN.TRL_TQU_ID != ''R'' THEN 1 ELSE 0 END AS "TOTAL TRAN COUNT",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "NO DISP",
	  CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED < TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "SHORT DISP",
      CASE WHEN TXN.TRL_POST_COMPLETION_CODE is null AND TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_AMT_COMPLETED > TXN.TRL_AMT_TXN THEN 1 ELSE 0 END AS "OVER DISPENSE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128, 142, 143) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 24, 26, 122) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (0, 50, 51, 133, 146, 246, 250) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 252) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS",
      TXN.TRL_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      LEFT JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''BNT''
	  LEFT JOIN CBC_TRAN_CODE CTRI ON TXN.TRL_TSC_CODE = CTRI.CTR_CODE AND ''I-'' || TXNC.TRL_ORIGIN_CHANNEL = CTRI.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON CBI.CBI_ID = (SELECT MIN(CBI_ID) FROM CBC_BIN WHERE CBI_BIN = TXNC.TRL_CARD_BIN)
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      LEFT JOIN CBC_BANK CBA_ACQ ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA_ACQ.CBA_CODE, 10, ''0'')
	  LEFT JOIN CBC_BILLER CBL ON CBL.CBL_ID = (SELECT MIN(CBL_ID) FROM CBC_BILLER WHERE CBL_CODE = TXNC.TRL_BILLER_CODE)
WHERE
	  TXN.TRL_TQU_ID IN (''F'', ''R'', ''C'')
      AND TXN.TRL_TSC_CODE NOT IN (44, 52)
      AND TXN.TRL_FRD_REV_INST_ID IS NOT NULL
      AND CTR.CTR_DEBIT_CREDIT = ''CREDIT''
      AND COALESCE(CBA.CBA_MNEM, TXN.TRL_ISS_NAME, '''') = {V_Iss_Name} 
	  AND (TXN.TRL_DEO_NAME != {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id})
      AND CBA.CBA_MNEM = {V_Iss_Name}
      AND {Txn_Date}
)
GROUP BY
      "TXN QUALIFIER",
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
	  "BILLER MNEM",
      "BANK CODE"
ORDER BY
      "TRAN MNEM" ASC,
      "TERMINAL" ASC,
      "BANK CODE" ASC	
	');	
	i_TRAILER_QUERY := null;
	
	UPDATE REPORT_DEFINITION SET 
		RED_HEADER_FIELDS = i_HEADER_FIELDS,
		RED_BODY_FIELDS = i_BODY_FIELDS,
		RED_TRAILER_FIELDS = i_TRAILER_FIELDS,
		RED_BODY_QUERY = i_BODY_QUERY,
		RED_TRAILER_QUERY = i_TRAILER_QUERY
	WHERE RED_NAME = 'Transaction Count Report';
	
END;
/