-- Tracking				Date			Name	Description
-- Revised Report		06-JULY-2021	WY		Revised reports based on spec

DECLARE
    i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;
BEGIN 
	
	i_BODY_QUERY := TO_CLOB('
	SELECT
      "BANK CODE",
      "BANK NAME",
      COUNT("NET COUNT") "NET COUNT",
      SUM("SumOfTxn") -  SUM("SumOfRev") "NET SETTLEMENT"
FROM (
SELECT
      LPAD(CBA.CBA_CODE, 4, ''0'') "BANK CODE",
      CBA.CBA_NAME "BANK NAME",
      TXN.TRL_ID "NET COUNT",
      CASE WHEN TXN.TRL_TQU_ID = ''F'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN TXN.TRL_AMT_TXN ELSE 0 END AS "SumOfTxn",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN TXN.TRL_AMT_TXN ELSE 0 END AS "SumOfRev"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BANK CBA ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA.CBA_CODE, 10, ''0'')
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'',''R'')
	  AND TXN.TRL_MCC_ID = ''6011''
      AND TXN.TRL_FRD_REV_INST_ID IS NULL
      AND TXN.TRL_DEO_NAME IS NULL
	  AND LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id}
      AND TXN.TRL_ISS_NAME = {V_Iss_Name}
      AND {Txn_Date}
	)
GROUP BY
      "BANK CODE",
      "BANK NAME"
ORDER BY
      "BANK CODE" ASC');
	  
	  i_TRAILER_QUERY := TO_CLOB('
SELECT
      COUNT("ITEM") "NET COUNT",
      SUM("SumOfTxn") -  SUM("SumOfRev") "NET SETTLEMENT"
FROM(
	SELECT CASE WHEN TXN.TRL_TQU_ID = ''F'' AND TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN TXN.TRL_AMT_TXN ELSE 0 END AS "SumOfTxn",
	  CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN TXN.TRL_AMT_TXN ELSE 0 END AS "SumOfRev",
	  TXN.TRL_ID AS "ITEM"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BANK CBA ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA.CBA_CODE, 10, ''0'')
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'',''R'')
	  AND TXN.TRL_MCC_ID = ''6011''
      AND TXN.TRL_FRD_REV_INST_ID IS NULL
      AND TXN.TRL_DEO_NAME IS NULL
	  AND LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') != {V_Acqr_Inst_Id}
      AND TXN.TRL_ISS_NAME = {V_Iss_Name}
      AND {Txn_Date})');
	
	UPDATE REPORT_DEFINITION set 
		RED_BODY_QUERY = i_BODY_QUERY,
		RED_TRAILER_QUERY = i_TRAILER_QUERY
	where RED_NAME = 'ATM Withdrawal as Issuer Bank Summary';
	
END;
/