-- TRANSACTION_LOG
create index IDX_TRL_TRL_PAN on TRANSACTION_LOG(TRL_PAN);
create index IDX_TRL_TRL_ORIGIN_ICH_NAME on TRANSACTION_LOG(TRL_ORIGIN_ICH_NAME);
create index IDX_TRL_ACQR_INST_ID on TRANSACTION_LOG (LPAD(TRL_ACQR_INST_ID, 10, '0'));

-- CBC_GL_ENTRY
create index IDX_GLE_GLE_DEBIT_DESC on CBC_GL_ENTRY(GLE_DEBIT_DESCRIPTION);
create index IDX_GLE_GLT_ID on CBC_GL_ENTRY(GLE_GLT_ID);

-- CBC_BIN
create index IDX_CBI_CBI_CBA_ID on CBC_BIN(CBI_CBA_ID);