  CREATE TABLE AUTH_PROCESSING_PROFILE
   (	
    "APPR_ID" NUMBER(19,0), 
	"APPR_NAME" VARCHAR2(50 BYTE), 
	"APPR_ON_US_FLAG" VARCHAR2(1 BYTE), 
	"APPR_AUT_ID" NUMBER(19,0), 
	"APPR_CARD_TRACK_GRP_CTG_ID" NUMBER(19,0), 
	"APPR_CUSTM_RESULT_GRP_CRG_ID" NUMBER(19,0), 
	"APPR_STATUS_CODE_GRP_SCG_ID" NUMBER(19,0), 
	"APPR_CREDIT_LIMT_GRP_CLG_ID" NUMBER(19,0), 
	"APPR_ROUTE_GROUP_RUG_ID" NUMBER(19,0), 
	"APPR_CVP_NAME" VARCHAR2(50 BYTE), 
	"APPR_ADD_FT_PERIOD" NUMBER(5,0), 
	"APPR_ERG_NAME" VARCHAR2(100 BYTE), 
	"APPR_ATG_NAME" VARCHAR2(50 BYTE), 
	"APPR_CARD_VALIDATION" VARCHAR2(50 BYTE), 
	"APPR_ISS_ID" NUMBER(19,0), 
	"APPR_LAST_UPDATE_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"APPR_ALP_ID" NUMBER(19,0), 
	"APPR_FEP_ID" NUMBER(19,0), 
	"APPR_TSP_ID" NUMBER(19,0)
   ) TABLESPACE AUTH_CONFIG_DATA_TS;
