alter table REPORT_DEFINITION modify RED_ID GENERATED BY DEFAULT AS IDENTITY restart start with 500;

delete from user_extra_branches;
alter table user_extra_branches drop constraint FK_USER_EXTRA_BRANCHES_BRANCH_ID;
alter table user_extra_branches modify BRANCH_ID VARCHAR2(20 CHAR);
alter table user_extra_branches add constraint FK_USER_EXTRA_BRANCHES_BRANCH_ID foreign key(BRANCH_ID) references branch(brc_code);