alter table report_category modify REC_ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table report_definition modify RED_ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table institution modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table user_extra modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table jhi_user modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table role_extra modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table app_resource modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);
alter table system_configuration modify ID GENERATED BY DEFAULT AS IDENTITY (start with 1100);