CREATE TABLE ATM_SUMMARY_COUNTERS (	
    ATNC_ID NUMBER(19,0), 
	ATNC_AST_ID NUMBER(19,0) NOT NULL ENABLE, 
	ATNC_ENTRY_DATE TIMESTAMP (6), 
	ATNC_COUNTER_TYPE VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "ATNC_PK" PRIMARY KEY (ATNC_ID)
 ) TABLESPACE AUTH_REPORT_DATA_TS;
 
 CREATE TABLE ATM_SUMMARY_VALUES (
    ATCV_ID NUMBER(19,0), 
	ATCV_ATNC_ID NUMBER(19,0) NOT NULL ENABLE, 
	ATCV_NOTE_TYPE VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	ATCV_NOTE_COUNT NUMBER(10,0) NOT NULL ENABLE, 
	CONSTRAINT "ATCV_PK" PRIMARY KEY (ATCV_ID)
 ) TABLESPACE AUTH_REPORT_DATA_TS;