DECLARE
	i_HEADER_FIELD CLOB;
	i_BODY_FIELD CLOB;
	i_TRAILER_FIELD CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;

BEGIN 

-- GL Handoff Block Sheet Listing
	-- Block Sheet Listing For Recycler

i_BODY_QUERY := TO_CLOB('
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      TXN.TRL_AMT_TXN "DEBIT",
      0 AS "CREDIT",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION 
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) "DEBIT",
      0 AS "CREDIT",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION 
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      TXN.TRL_AMT_TXN "DEBIT",
      0 AS "CREDIT",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401401 THEN TXN.TRL_AMT_TXN 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401407 THEN TXN.TRL_AMT_TXN ELSE 0 END "DEBIT",
      0 AS "CREDIT",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246)  
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION 
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401404 THEN COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401410 THEN COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) ELSE 0 END "DEBIT",
      0 AS "CREDIT",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
START SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      0 AS "DEBIT",
      TXN.TRL_AMT_TXN "CREDIT",     
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_CREDIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION  
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      0 AS "DEBIT",
      TXN.TRL_AMT_TXN "CREDIT",     
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION  
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      TXN.TRL_DEST_STAN "CODE",
      0 AS "DEBIT",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080024537044 THEN TXN.TRL_AMT_TXN 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080024537050 THEN TXN.TRL_AMT_TXN ELSE 0 END "CREDIT",    
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      GLE.GLE_DEBIT_DESCRIPTION "DESCRIPTION"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
ORDER BY
      "BRANCH CODE" ASC,
      "GL ACCOUNT NUMBER" ASC,
      "GL ACCOUNT NAME" ASC
END
');

i_TRAILER_QUERY := TO_CLOB('
SELECT 
      SUM(NVL("TOTAL DEBIT", 0)) "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
(
SELECT
      SUM(NVL(TXN.TRL_AMT_TXN, 0)) "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT 
      SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT 
      SUM(NVL(TXN.TRL_AMT_TXN, 0)) "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT 
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401401 THEN SUM(NVL(TXN.TRL_AMT_TXN, 0)) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401407 THEN SUM(NVL(TXN.TRL_AMT_TXN, 0)) ELSE 0 END "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246)  
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME, 
      GLA.GLA_NUMBER
UNION
SELECT 
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401404 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401410 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) ELSE 0 END "TOTAL DEBIT",
      0 AS "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME, 
      GLA.GLA_NUMBER
)
START SELECT 
      0 AS "TOTAL DEBIT",
      SUM(NVL("TOTAL CREDIT", 0)) "TOTAL CREDIT"
FROM
(
SELECT
      0 AS "TOTAL DEBIT",
      SUM(NVL(TXN.TRL_AMT_TXN, 0)) "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT 
      0 AS "TOTAL DEBIT",
      SUM(NVL(TXN.TRL_AMT_TXN, 0)) "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
UNION
SELECT 
      0 AS "TOTAL DEBIT",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080024537044 THEN SUM(NVL(TXN.TRL_AMT_TXN, 0)) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080024537050 THEN SUM(NVL(TXN.TRL_AMT_TXN, 0)) ELSE 0 END "TOTAL CREDIT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME, 
      GLA.GLA_NUMBER
)
END
');

UPDATE REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY, RED_TRAILER_QUERY = i_TRAILER_QUERY WHERE RED_NAME = 'Block Sheet Listing For Recycler';


-- GL Handoff Files
	-- ATM CBC GL REC 001

i_BODY_QUERY := TO_CLOB('

SELECT
      SUM("Tran Amount") "Tran Amount",
      "BRANCH CODE",
      "A/C Number",
      "Currency Code of Account Number",
      "Part Tran Indicator",
      "Tran Particular",
      "Reference Currency Code",
      "Value Date",
      "Third Party Tran Description",
      "TRAN_DATE"
FROM(
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''D'' AS "Part Tran Indicator",
      SUM(TXN.TRL_AMT_TXN) "Tran Amount",
      GLE.GLE_DEBIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_DEBIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      GLE.GLE_DEBIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''D'' AS "Part Tran Indicator",
      SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) "Tran Amount",
      GLE.GLE_DEBIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_DEBIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      GLE.GLE_DEBIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''D'' AS "Part Tran Indicator",
      SUM(TXN.TRL_AMT_TXN) AS "Tran Amount",
      GLE.GLE_DEBIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_DEBIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      GLE.GLE_DEBIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''D'' AS "Part Tran Indicator",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401401 THEN SUM(TXN.TRL_AMT_TXN) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401407 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END "Tran Amount",
      GLE.GLE_DEBIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_DEBIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246)  
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLE.GLE_DEBIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''D'' AS "Part Tran Indicator",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401404 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401410 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) ELSE 0 END "Tran Amount",
      GLE.GLE_DEBIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_DEBIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLE.GLE_DEBIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
)
GROUP BY
    "BRANCH CODE",
    "A/C Number",
    "Currency Code of Account Number",
    "Part Tran Indicator",
    "Tran Particular",
    "Reference Currency Code",
    "Value Date",
    "Third Party Tran Description",
    "TRAN_DATE"
ORDER BY
      "BRANCH CODE"
START SELECT
      SUM("Tran Amount") "Tran Amount",
      "BRANCH CODE",
      "A/C Number",
      "Currency Code of Account Number",
      "Part Tran Indicator",
      "Tran Particular",
      "Reference Currency Code",
      "Value Date",
      "Third Party Tran Description",
      "TRAN_DATE"
FROM(
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''C'' AS "Part Tran Indicator",
      SUM(TXN.TRL_AMT_TXN) "Tran Amount",
      GLE.GLE_CREDIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_CREDIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      GLE.GLE_CREDIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''C'' AS "Part Tran Indicator",
      SUM(TXN.TRL_AMT_TXN) "Tran Amount",
      GLE.GLE_CREDIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_CREDIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      GLE.GLE_CREDIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "A/C Number",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Currency Code of Account Number",
      ''C'' AS "Part Tran Indicator",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080024537044 THEN SUM(TXN.TRL_AMT_TXN) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080024537050 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END "Tran Amount",
      GLE.GLE_CREDIT_DESCRIPTION "Tran Particular",
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END AS "Reference Currency Code",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "Value Date",
      GLE.GLE_CREDIT_DESCRIPTION "Third Party Tran Description",
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'') "TRAN_DATE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY 
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      CASE WHEN TXN.TRL_TXN_CUR_ISO_ID = 608 THEN ''PHP'' ELSE ''PHP'' END,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLE.GLE_CREDIT_DESCRIPTION,
      TO_CHAR(TXN.TRL_DATETIME_LOCAL_TXN, ''MM-DD-YYYY'')
)
GROUP BY
    "BRANCH CODE",
    "A/C Number",
    "Currency Code of Account Number",
    "Part Tran Indicator",
    "Tran Particular",
    "Reference Currency Code",
    "Value Date",
    "Third Party Tran Description",
    "TRAN_DATE"
ORDER BY
      "BRANCH CODE"
END
');

UPDATE REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY WHERE RED_NAME = 'ATM CBC GL REC 001';


-- GL Handoff Final Proof Sheets
	-- Final Proof Sheet For Recycler

i_BODY_QUERY := TO_CLOB('
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      SUM(TXN.TRL_AMT_TXN) "DEBITS",
      0 AS "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) "DEBITS",
      0 AS "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      SUM(TXN.TRL_AMT_TXN) "DEBITS",
      0 AS "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401401 THEN SUM(TXN.TRL_AMT_TXN) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401407 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END "DEBITS",
      0 AS "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246)  
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080012401404 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080012401410 THEN SUM(COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT)) ELSE 0 END "DEBITS",
      0 AS "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED = ''Y''
      LEFT JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_DEBIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND COALESCE(TXN.TRL_ISS_CHARGE_AMT, TXN.TRL_ACQ_CHARGE_AMT) is not null
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLA.GLA_NAME
ORDER BY
      "BRANCH CODE" ASC
START SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      0 AS "DEBITS",
      SUM(TXN.TRL_AMT_TXN) "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (1,128) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      0 AS "DEBITS",
      SUM(TXN.TRL_AMT_TXN) "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (50,250) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      GLA.GLA_NAME
UNION
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      GLA.GLA_NUMBER "GL ACCOUNT NUMBER",
      GLA.GLA_NAME "GL ACCOUNT NAME",
      0 AS "DEBITS",
      CASE WHEN TXN.TRL_ISS_NAME = ''CBC'' AND GLA.GLA_NUMBER = 50080024537044 THEN SUM(TXN.TRL_AMT_TXN) 
           WHEN ((TXN.TRL_DEO_NAME = ''CBC'' AND TXN.TRL_ISS_NAME = ''CBS'') OR (TXN.TRL_DEO_NAME = ''CBS'' AND TXN.TRL_ISS_NAME = ''CBC'')) AND GLA.GLA_NUMBER = 50080024537050 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END "CREDITS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_GL_ENTRY GLE ON TXN.TRL_TSC_CODE = GLE.GLE_TRAN_TYPE 
         AND GLE.GLE_TRAN_CHANNEL=''CDM''
         AND GLE.GLE_GLT_ID = (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = ''Recycler'')
         AND GLE.GLE_SVC_ENABLED is null
      JOIN CBC_GL_ACCOUNT GLA ON GLE.GLE_CREDIT_ACCOUNT = GLA.GLA_NAME
      LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      LEFT JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      LEFT JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TRL_TSC_CODE in (146,246) 
      AND NVL(CPD.CPD_CODE,0) NOT IN (''80'',''81'',''82'',''83'')
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXNC.TRL_ORIGIN_CHANNEL IN (''CDM'',''BRM'')
      AND {Branch_Code}
      AND {Txn_Date}
GROUP BY
      ABR.ABR_CODE,
      GLA.GLA_NUMBER,
      TXN.TRL_DEO_NAME,
      TXN.TRL_ISS_NAME,
      GLA.GLA_NAME
ORDER BY
      "BRANCH CODE" ASC
END
');

UPDATE REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY WHERE RED_NAME = 'Final Proof Sheet For Recycler';


-- Inter-Entity ATM Withdrawal Transactions
	-- Inter-Entity ATM Withdrawal as Acquirer Bank

i_BODY_QUERY := TO_CLOB('
SELECT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      ABR.ABR_CODE "BRANCH CODE",
      ABR.ABR_NAME "BRANCH NAME",
      SUBSTR(AST.AST_TERMINAL_ID, -4) "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      TXN.TRL_DEST_STAN "SEQ NUMBER",
      TXN.TRL_PAN "ATM CARD NUMBER",
      TXN.TRL_PAN_EKY_ID,
      TXN.TRL_DATETIME_LOCAL_TXN "TIME",
      CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TQU_ID != ''R'' THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DR AMOUNT",
      CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CR AMOUNT",
      TXN.TRL_ACTION_RESPONSE_CODE "VOID CODE",
      ARC.ARC_NAME "COMMENT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'', ''R'')
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_RVRSL_TYPE = 0
      AND {Deo_Name}
      AND {Iss_Name}
      AND {Branch_Code}
      AND {Terminal}
      AND {Txn_Date}
ORDER BY
      ABR.ABR_CODE ASC,
      AST.AST_TERMINAL_ID ASC,
      TXN.TRL_SYSTEM_TIMESTAMP ASC,
      TXN.TRL_DEST_STAN ASC
START SELECT
      "BRANCH CODE",
      "BRANCH NAME",
      "TERMINAL",
      "LOCATION",
      SUM("A/R PER TERMINAL") "A/R PER TERMINAL",
      SUM("A/R PER TERMINAL") "TOTAL A/R AMOUNT",
      COUNT("ITEMS") "ITEMS",
      7.50 * COUNT("ITEMS") AS "TXN FEE"
FROM (
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      ABR.ABR_NAME "BRANCH NAME",
      SUBSTR(AST.AST_TERMINAL_ID, -4) "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      TXN.TRL_AMT_TXN "A/R PER TERMINAL",
      TXN.TRL_ID "ITEMS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'', ''R'')
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_RVRSL_TYPE = 0
      AND {Deo_Name}
      AND {Iss_Name}
      AND {Branch_Code}
      AND {Terminal}
      AND {Txn_Date}
)
GROUP BY
      "BRANCH CODE",
      "BRANCH NAME",
      "TERMINAL",
      "LOCATION"
ORDER BY
      "BRANCH CODE" ASC,
      "BRANCH NAME" ASC,
      "TERMINAL" ASC
END
');

i_TRAILER_QUERY := TO_CLOB('
SELECT
      COUNT(TXN.TRL_ID) "TOTAL TRAN",
      SUM(TXN.TRL_AMT_TXN) "TOTAL"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'', ''R'')
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_RVRSL_TYPE = 0
      AND {Deo_Name}
      AND {Iss_Name}
      AND {Branch_Code}
      AND {Terminal}
      AND {Txn_Date}
START SELECT
      SUM(TXN.TRL_AMT_TXN) "A/R PER TERMINAL",
      COUNT(TXN.TRL_ID) "ITEMS",
      7.50 * COUNT(TXN.TRL_ID) "TOTAL TXN FEE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
WHERE
      TXN.TRL_TSC_CODE IN (1, 128)
      AND TXN.TRL_TQU_ID IN (''F'', ''R'')
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_RVRSL_TYPE = 0
      AND {Deo_Name}
      AND {Iss_Name}
      AND {Txn_Date}
END
');

UPDATE REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY, RED_TRAILER_QUERY = i_TRAILER_QUERY WHERE RED_NAME = 'Inter-Entity ATM Withdrawal as Acquirer Bank';

END;
/