DECLARE
	i_HEADER_FIELD CLOB;
	i_BODY_FIELD CLOB;
	i_TRAILER_FIELD CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;

BEGIN 

-- New Transactions Reports
	-- List of Moving Cash Transactions

i_BODY_QUERY := TO_CLOB('
SELECT
      ABR.ABR_CODE "BRANCH CODE",
      ABR.ABR_NAME "BRANCH NAME",
      SUBSTR(AST.AST_TERMINAL_ID, -4) "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      TXN.TRL_DATETIME_LOCAL_TXN "TIME",
      TXN.TRL_DEST_STAN "SEQ NUMBER",
      SUBSTR(TXN.TRL_RRN, 7, 6) "TRACE NUMBER",
      CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
      CMV.CMV_TXN_REF_NO "TRAN REF NO",
      CBA.CBA_MNEM "BANK MNEM",
      TXN.TRL_PAN "ATM CARD NUMBER",
      TXN.TRL_PAN_EKY_ID,
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      CMV.CMV_RECV_MOBILE"TO MOBILE NO",
      TXN.TRL_AMT_TXN "AMOUNT",
      NVL(TXN.TRL_ISS_CHARGE_AMT, 0) "TRAN FEE",
      ''00 - Approved'' "COMMENT"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CBC_MOVING_CASH CMV ON TXN.TRL_RRN = CMV.CMV_TXN_REF_NO
WHERE
      TXN.TRL_TSC_CODE = 143
      AND TXN.TRL_TQU_ID = ''F''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND {Branch_Code}
      AND {Terminal}
      AND {Txn_Date}
ORDER BY
      ABR.ABR_CODE ASC,
      AST.AST_TERMINAL_ID ASC,
      TXN.TRL_SYSTEM_TIMESTAMP ASC,
      TXN.TRL_DEST_STAN ASC,
      TXN.TRL_RRN ASC
START SELECT
      ''ATM WITHDRAWAL'' "TXN TYPE",
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN COUNT(TXN.TRL_ID) ELSE 0 END AS "SA VOL",
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END AS "SA AMT",
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN SUM(NVL(TXN.TRL_ISS_CHARGE_AMT, 0)) ELSE 0 END AS "SA FEE",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN COUNT(TXN.TRL_ID) ELSE 0 END AS "CA VOL",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END AS "CA AMT",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN SUM(NVL(TXN.TRL_ISS_CHARGE_AMT, 0)) ELSE 0 END AS "CA FEE"
FROM
      TRANSACTION_LOG TXN
      JOIN ACCOUNT_TYPE ATP ON TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = ATP.ATP_ID
WHERE
      TXN.TRL_TSC_CODE = 143
      AND TXN.TRL_TQU_ID = ''F''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND {Txn_Date}
GROUP BY
      ATP.ATP_ISO_ID
END
');

i_TRAILER_QUERY := TO_CLOB('
SELECT
       SUM(TXN.TRL_AMT_TXN) "AMOUNT",
       SUM(NVL(TXN.TRL_ISS_CHARGE_AMT, 0)) "TRAN FEE"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
      LEFT JOIN CBC_MOVING_CASH CMC ON TXN.TRL_RRN = CMC.CMV_TXN_REF_NO
WHERE
      TXN.TRL_TSC_CODE = 143
      AND TXN.TRL_TQU_ID = ''F''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND {Branch_Code}
      AND {Txn_Date}
START SELECT
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN COUNT(TXN.TRL_ID) ELSE 0 END AS "SA VOL",
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END AS "SA AMT",
      CASE WHEN ATP.ATP_ISO_ID = 10 THEN SUM(NVL(TXN.TRL_ISS_CHARGE_AMT, 0)) ELSE 0 END AS "SA FEE",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN COUNT(TXN.TRL_ID) ELSE 0 END AS "CA VOL",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN SUM(TXN.TRL_AMT_TXN) ELSE 0 END AS "CA AMT",
      CASE WHEN ATP.ATP_ISO_ID = 20 THEN SUM(NVL(TXN.TRL_ISS_CHARGE_AMT, 0)) ELSE 0 END AS "CA FEE"
FROM
      TRANSACTION_LOG TXN
      JOIN ACCOUNT_TYPE ATP ON TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = ATP.ATP_ID
WHERE
      TXN.TRL_TSC_CODE = 143
      AND TXN.TRL_TQU_ID = ''F''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND {Txn_Date}
GROUP BY
      ATP.ATP_ISO_ID
END
');

UPDATE REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY, RED_TRAILER_QUERY = i_TRAILER_QUERY WHERE RED_NAME = 'List of Moving Cash Transactions';


END;
/