INSERT INTO SYSTEM_CONFIGURATION (ID, NAME, DESCRIPTION, CONFIG, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE) VALUES
((SELECT MAX(ID) + 1 FROM SYSTEM_CONFIGURATION), 'security.password.expiry','Password Expiry(days)','365',
'system',current_timestamp,null,null);

INSERT INTO SYSTEM_CONFIGURATION (ID, NAME, DESCRIPTION, CONFIG, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE) VALUES
((SELECT MAX(ID) + 1 FROM SYSTEM_CONFIGURATION), 'security.max.login.retry','Maximum login retry','3',
'system',current_timestamp,null,null);

INSERT INTO SYSTEM_CONFIGURATION (ID, NAME, DESCRIPTION, CONFIG, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE) VALUES
((SELECT MAX(ID) + 1 FROM SYSTEM_CONFIGURATION), 'security.dormant.period','Dormant period(days)','365',
'system',current_timestamp,null,null);