DECLARE
	i_BODY_FIELD CLOB;
	i_TRAILER_FIELD CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;
BEGIN 

-- List of Recycler Transactions
	i_BODY_QUERY := TO_CLOB('		
select 
	  (ABR.ABR_CODE || '' '' || ABR.ABR_NAME) "BRANCH",
	  (SUBSTR(AST.AST_TERMINAL_ID, -4) || '' '' || AST.AST_ALO_LOCATION_ID) "TERMINAL",
	  CASE WHEN TXNC.TRL_IS_CARDLESS=0 AND CTR.CTR_DEBIT_CREDIT=''DEBIT'' THEN ''CARDED TRANSACTIONS - DEBIT FROM ACCOUNT''
	    WHEN TXNC.TRL_IS_CARDLESS=0 AND CTR.CTR_DEBIT_CREDIT=''CREDIT'' THEN ''CARDED TRANSACTIONS - CASH DEPOSIT''
	    WHEN TXNC.TRL_IS_CARDLESS=1 AND CTR.CTR_DEBIT_CREDIT=''CREDIT'' THEN ''CARDLESS TRANSACTIONS - CASH DEPOSIT''
	    ELSE ''CARDLESS TRANSACTIONS - OTHERS''
	    END AS "TRANSACTION GROUP",
	  CASE WHEN TSC.TSC_CODE = 1 THEN ''ATM WITHDRAWAL'' 
	    WHEN TSC.TSC_CODE = 128 THEN ''ATM WITHDRAWAL'' 
	    WHEN TSC.TSC_CODE = 142 THEN ''MOVING CASH - EMERGENCY CASH (NOW)''
	    WHEN TSC.TSC_CODE = 143 THEN ''MOVING CASH - PAY TO MOBILE (JUMP)''
	    WHEN TSC.TSC_CODE = 46 THEN ''INSTAPAY FUND TRANSFER''
	    WHEN TSC.TSC_CODE = 47 THEN ''PESONET FUND TRANSFER''
	    WHEN TSC.TSC_CODE = 21 THEN ''CASH DEPOSIT TRANSFER''
	    WHEN TSC.TSC_CODE = 26 THEN ''CASH DEPOSIT TRANSFER''
	    WHEN TSC.TSC_CODE = 250 THEN ''BILLS PAYMENT''
	    WHEN TSC.TSC_CODE = 252 THEN ''PREPAID AUTO RELOAD''
	    WHEN TSC.TSC_CODE = 246 THEN ''BEEP LOADING''
	    WHEN TSC.TSC_CODE = 251 THEN ''RFID LOADING''
	    ELSE TSC.TSC_DESCRIPTION 
	    END AS "TRANSACTION TYPE",
	  TXN.TRL_SYSTEM_TIMESTAMP "DATE",
	  TXN.TRL_SYSTEM_TIMESTAMP "TIME",
	  TXN.TRL_DEST_STAN "SEQ NO",
	  SUBSTR(TXN.TRL_RRN, 7, 6) "TRACE NO",
	  CTR.CTR_MNEM "TRAN MNEM",
	  CASE WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 10 THEN ''SA'' WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 20 THEN ''CA'' ELSE '''' END AS "TRAN TYPE",
	  CBA.CBA_MNEM "BANK MNEM",
	  TXN.TRL_PAN "CARD NO",
	  TXN.TRL_PAN_EKY_ID "CARD NO_ENCKEY",
	  NVL(TXN.TRL_ACCOUNT_1_ACN_ID, TXN.TRL_ACCOUNT_2_ACN_ID) "ACC NO",
	  NVL(TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID, TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID) "ACC NO_ENCKEY",
	  NVL(TXN.TRL_AMT_TXN,0) "TRANS AMOUNT",
	  NVL(TRL_ISS_CHARGE_AMT, NVL(TRL_ACQ_CHARGE_AMT,0)) "TRAN FEE",
	  (TXN.TRL_ACTION_RESPONSE_CODE || '' - '' || ARC.ARC_NAME) "REMARKS" 
	from 
	  TRANSACTION_LOG TXN
	  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
	  JOIN TRANSACTION_CODE TSC ON TXN.TRL_TSC_CODE = TSC.TSC_CODE
	  JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
	  JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
	  JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
	  JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
	  JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
	  JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE
	where 
	  TXN.TRL_TQU_ID = ''F''
	  AND TXN.TRL_ACTION_RESPONSE_CODE < 100
	  AND TXNC.TRL_ORIGIN_CHANNEL = ''BRM''
	  AND {Txn_Date}
	order by ABR_CODE, TERMINAL, "TRANSACTION GROUP", "TRANSACTION TYPE", "DATE", "TIME"	
	');
	
	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY where RED_NAME = 'List of Recycler Transactions';
	
-- Summary of Recycler Transactions
	i_BODY_QUERY := TO_CLOB('		
select 
  	  BRANCH,
	  TERMINAL,
	  "TRANSACTION GROUP",
	  "TRANSACTION TYPE",
	  SUM(CASE WHEN TRL_ISS_NAME IN (''CBC'', ''CBS'') AND TRL_IS_INTER_ENTITY = 0 AND CPD_NAME NOT IN (''CASH CARD'', ''EMV CASH CARD'') THEN NVL(TRL_AMT_TXN,0) ELSE 0 END) AS "ONUS",
	  SUM(CASE WHEN TRL_IS_INTER_ENTITY = 1 AND CPD_NAME NOT IN (''CASH CARD'', ''EMV CASH CARD'') THEN NVL(TRL_AMT_TXN,0) ELSE 0 END) AS "INTER ENTITY",
	  SUM(CASE WHEN TRL_ISS_NAME IS NULL AND CPD_NAME NOT IN (''CASH CARD'', ''EMV CASH CARD'') THEN NVL(TRL_AMT_TXN,0) ELSE 0 END) AS "OTHER BANKS",
	  SUM(CASE WHEN CPD_NAME IN (''CASH CARD'', ''EMV CASH CARD'') THEN NVL(TRL_AMT_TXN,0) ELSE 0 END) AS "CASH CARD",
	  SUM(CASE WHEN "TRANSACTION GROUP" = ''CARDED TRANSACTIONS - DEBIT FROM ACCOUNT'' THEN NVL(TRL_AMT_TXN,0) ELSE NULL END) AS "TOTAL DISPENSED",
	  SUM(CASE WHEN "TRANSACTION GROUP" != ''CARDED TRANSACTIONS - DEBIT FROM ACCOUNT'' THEN NVL(TRL_AMT_TXN,0) ELSE NULL END) AS "TOTAL DEPOSIT"
	FROM (
    select (ABR.ABR_CODE || '' '' || ABR.ABR_NAME) "BRANCH",
	  (SUBSTR(AST.AST_TERMINAL_ID, -4) || '' '' || AST.AST_ALO_LOCATION_ID) "TERMINAL",
	  CASE WHEN TXNC.TRL_IS_CARDLESS=0 AND CTR.CTR_DEBIT_CREDIT=''DEBIT'' THEN ''CARDED TRANSACTIONS - DEBIT FROM ACCOUNT''
	    WHEN TXNC.TRL_IS_CARDLESS=0 AND CTR.CTR_DEBIT_CREDIT=''CREDIT'' THEN ''CARDED TRANSACTIONS - CASH DEPOSIT''
	    WHEN TXNC.TRL_IS_CARDLESS=1 AND CTR.CTR_DEBIT_CREDIT=''CREDIT'' THEN ''CARDLESS TRANSACTIONS - CASH DEPOSIT''
	    ELSE ''CARDLESS TRANSACTIONS - OTHERS''
	    END AS "TRANSACTION GROUP",
	  CASE WHEN TSC.TSC_CODE = 1 THEN ''ATM WITHDRAWAL''
	    WHEN TSC.TSC_CODE = 128 THEN ''ATM WITHDRAWAL'' 
	    WHEN TSC.TSC_CODE = 142 THEN ''MOVING CASH - EMERGENCY CASH (NOW)''
	    WHEN TSC.TSC_CODE = 143 THEN ''MOVING CASH - PAY TO MOBILE (JUMP)''
	    WHEN TSC.TSC_CODE = 46 THEN ''INSTAPAY FUND TRANSFER''
	    WHEN TSC.TSC_CODE = 47 THEN ''PESONET FUND TRANSFER''
	    WHEN TSC.TSC_CODE = 21 THEN ''CASH DEPOSIT TRANSFER''
	    WHEN TSC.TSC_CODE = 26 THEN ''CASH DEPOSIT TRANSFER''
	    WHEN TSC.TSC_CODE = 250 THEN ''BILLS PAYMENT''
	    WHEN TSC.TSC_CODE = 252 THEN ''PREPAID AUTO RELOAD''
	    WHEN TSC.TSC_CODE = 246 THEN ''BEEP LOADING''
	    WHEN TSC.TSC_CODE = 251 THEN ''RFID LOADING''
	    ELSE TSC.TSC_DESCRIPTION 
      END AS "TRANSACTION TYPE",
      TXNC.TRL_IS_INTER_ENTITY,
      CPD.CPD_NAME,
      TXN.TRL_AMT_TXN,
      TXN.TRL_ISS_NAME
	from 
	  TRANSACTION_LOG TXN
	  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
	  JOIN TRANSACTION_CODE TSC ON TXN.TRL_TSC_CODE = TSC.TSC_CODE
	  JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND CTR.CTR_CHANNEL = ''CDM''
	  JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
	  JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
      JOIN CARD_PRODUCT CPD ON CRD.CRD_CPD_ID = CPD.CPD_ID
	  JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
	  JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
	  JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE   
	where 
	  TXN.TRL_TQU_ID = ''F''
	  AND TXN.TRL_ACTION_RESPONSE_CODE < 100
	  AND TXNC.TRL_ORIGIN_CHANNEL = ''BRM''
	  AND {Txn_Date}
	)
	group by BRANCH, TERMINAL, "TRANSACTION GROUP", "TRANSACTION TYPE"
	order by BRANCH, TERMINAL, "TRANSACTION GROUP", "TRANSACTION TYPE"
	');
	
	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY where RED_NAME = 'Summary of Recycler Transactions';
	
-- Transaction Count Report
	i_BODY_QUERY := TO_CLOB('
SELECT
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
      "BANK CODE",
      SUM("APPROVED TRAN COUNT") "APPROVED TRAN COUNT",
      SUM("REJECTED TRAN COUNT") "REJECTED TRAN COUNT",
      COUNT("TOTAL TRAN COUNT") "TOTAL TRAN COUNT",
      0 "SHORT DISPENSE COUNT",
      0 "NO DISPENSE COUNT",
      0 "OVER DISPENSE COUNT",
      0 "HARDWARE FAILURE COUNT",
      SUM("CASH DISPENSED") "CASH DISPENSED",
      SUM("DEPOSITS") "DEPOSITS",
      SUM("BILL PAYMENTS") "BILL PAYMENTS",
      SUM("TRANSFERS") "TRANSFERS"
FROM (
SELECT
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) "TERMINAL",
      CBA.CBA_MNEM "BANK MNEM",
      CASE 
		WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_TSC_CODE <> 44
			THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CHANNEL=''BNT'' AND CTR_CODE=TXN.TRL_TSC_CODE AND CTR_DEBIT_CREDIT=''DEBIT'')
		WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_TSC_CODE = 44
			THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CHANNEL=''BNT'' AND CTR_CODE=TXN.TRL_TSC_CODE AND CTR_DEBIT_CREDIT=''CREDIT'')
        ELSE CTR.CTR_MNEM END AS "TRAN MNEM", 
      LPAD(CBA.CBA_CODE, 4, 0) "BANK CODE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE != 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      TXN.TRL_ID "TOTAL TRAN COUNT",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 26) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE = 50 THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 42, 43, 44, 45, 52) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
WHERE
      TXN.TRL_TSC_CODE IN (1, 128, 21, 26, 31, 40, 42, 43, 44, 45, 50, 52)
      AND TXN.TRL_TQU_ID = ''F''
      AND CTR.CTR_DEBIT_CREDIT = ''DEBIT''
      AND {Txn_Date}
)
GROUP BY
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
      "BANK CODE"
ORDER BY
      "TRAN MNEM" ASC,
      "TERMINAL" ASC,
      "BANK CODE" ASC	
	');
	
	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY where RED_NAME = 'Transaction Count Report';
	
END;
/