DECLARE
	i_HEADER_FIELD CLOB;
	i_BODY_FIELD CLOB;
	i_TRAILER_FIELD CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;

BEGIN 

-- ATM Daily Exception Messages
	i_BODY_QUERY := TO_CLOB('		
    SELECT
      AST.AST_ARE_NAME "REGION",
      AST.AST_TERMINAL_ID "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      AJL.AJL_TIMESTAMP "DATE TIME",
      AJL.AJL_EJ_DATA "EXCEPTION"
	FROM
      ATM_STATIONS AST
      JOIN ATM_JOURNAL_LOG AJL ON AST.AST_ID = AJL.AJL_AST_ID
      AND {Txn_Date}
	ORDER BY
      AST.AST_ARE_NAME ASC,
      AST.AST_TERMINAL_ID ASC,
      AJL.AJL_TIMESTAMP ASC
	');

	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY where RED_NAME = 'ATM Daily Exception Messages';

END;
/