DECLARE
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;
BEGIN 

-- Daily Payment Transaction Report TellerCard Summary  by Utility Company
	i_BODY_QUERY := TO_CLOB('		
SELECT
	"BILLER NAME",
	COUNT("TOTAL TRANS") "TOTAL TRANS",
	SUM("TOTAL AMOUNT") "TOTAL AMOUNT"
FROM (
	SELECT
      		CBL.CBL_NAME "BILLER NAME",
      		TXN.TRL_ID "TOTAL TRANS",
      		TXN.TRL_AMT_TXN "TOTAL AMOUNT"
		FROM
      		TRANSACTION_LOG TXN
      		JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      		JOIN CBC_BILLER CBL ON LPAD(TXNC.TRL_BILLER_CODE, 3, ''0'') = LPAD(CBL.CBL_CODE, 3, ''0'')
		WHERE
      		TXN.TRL_TSC_CODE = 50
      		AND TXN.TRL_TQU_ID = ''F''
      		AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      		AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
            AND {Iss_Name}
      		AND {Txn_Date}
	)
	GROUP BY
      "BILLER NAME"
	ORDER BY
      "BILLER NAME" ASC		
	');
	
	i_TRAILER_QUERY := TO_CLOB('
SELECT
	COUNT(TXN.TRL_ID) "TOTAL TRANS",
      	SUM(TXN.TRL_AMT_TXN) "TOTAL AMOUNT"
	FROM
      	TRANSACTION_LOG TXN
	WHERE
      	TXN.TRL_TSC_CODE = 50
      	AND TXN.TRL_TQU_ID = ''F''	  
      	AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      	AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
        AND {Iss_Name}
      	AND {Txn_Date}   
	');

	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY, RED_TRAILER_QUERY = i_TRAILER_QUERY where RED_NAME = 'Daily Payment Transaction Report TellerCard Summary  by Utility Company';
	
-- Daily Payment Transaction Report by Acquirer/Issuer Branch
	i_BODY_QUERY := TO_CLOB('
SELECT
      {Branch_Code} "BRANCH CODE",
      {Branch_Name} "BRANCH NAME",
      TXNC.TRL_ORIGIN_CHANNEL "CHANNEL",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      LPAD(CBA.CBA_CODE, 4, 0) "BANK CODE",
      TXN.TRL_CARD_ACPT_TERMINAL_IDENT "TERMINAL",
      CBA.CBA_MNEM "BANK MNEM",
      CBL.CBL_SETTLEMENT_TYPE "MN",
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      TXN.TRL_DATETIME_LOCAL_TXN "TIME",
      TXN.TRL_DEST_STAN "SEQ NUMBER",
      TXN.TRL_AMT_TXN  "AMOUNT",
      TXN.TRL_CUSTOM_DATA "SUBSCRIBER ACCT NUMBER",
      TXN.TRL_CUSTOM_DATA_EKY_ID
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN CBC_BILLER CBL ON LPAD(TXNC.TRL_BILLER_CODE, 3, ''0'') = LPAD(CBL.CBL_CODE, 3, ''0'')
      {Join_Criteria}
WHERE
      TXN.TRL_TSC_CODE = 50
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND {Txn_Criteria}
	  AND {Deo_Name}
	  AND {Iss_Name}
      AND {Txn_Date}
ORDER BY
      CBA.CBA_CODE ASC,
      TXN.TRL_SYSTEM_TIMESTAMP ASC,
      TXN.TRL_DEST_STAN ASC
	');
	
	i_TRAILER_QUERY := TO_CLOB('
SELECT
      CBL.CBL_SETTLEMENT_TYPE "MN",
      COUNT(TXN.TRL_ID) "TOTAL TRAN",
      SUM(TXN.TRL_AMT_TXN) "TOTAL"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID = TXNC.TRL_ID
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN CBC_BILLER CBL ON LPAD(TXNC.TRL_BILLER_CODE, 3, ''0'') = LPAD(CBL.CBL_CODE, 3, ''0'')
      {Join_Criteria}
WHERE
      TXN.TRL_TSC_CODE = 50
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND {Txn_Criteria}
	  AND {Deo_Name}
	  AND {Iss_Name}
      AND {Txn_Date}
GROUP BY
      CBL.CBL_SETTLEMENT_TYPE
	');
	
	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY, RED_TRAILER_QUERY = i_TRAILER_QUERY where RED_NAME = 'Daily Payment Transaction Report by Acquirer/Issuer Branch';
END;
/