DECLARE
	i_HEADER_FIELD CLOB;
	i_BODY_FIELD CLOB;
	i_TRAILER_FIELD CLOB;
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;

BEGIN 

-- Cash Card Daily Transaction Summary
	i_BODY_QUERY := TO_CLOB('
	select 
  		BRC.BRC_CODE "BRANCH CODE",
  		BRC.BRC_NAME "BRANCH NAME",
		case when TXNC.TRL_IS_CORPORATE_CARD = 0 then ''CASH CARD RETAIL'' else ''CASH CARD CORPORATE'' end "TRANSACTION GROUP",
		TXNC.TRL_ORIGIN_CHANNEL "CHANNEL",
		sum(ACN.ACN_BALANCE_1) "BALANCE",
		TXNC.TRL_IS_CORPORATE_CARD "RETAIL_CORPORATE",
		sum(case when CTR.CTR_DEBIT_CREDIT = ''DEBIT'' then TXN.TRL_AMT_TXN else 0 end) "TOTAL DEBIT",
		sum(case when CTR.CTR_DEBIT_CREDIT = ''CREDIT'' then TXN.TRL_AMT_TXN else 0 end) "TOTAL CREDIT"
	from 
	  TRANSACTION_LOG txn 
	  left join CARD CRD on TXN.TRL_PAN=CRD.CRD_PAN 
	  left join TRANSACTION_LOG_CUSTOM TXNC on TXN.TRL_ID=TXNC.TRL_ID
	  left join BRANCH BRC on TXNC.TRL_CARD_BRANCH = BRC.BRC_CODE 
	  left join CARD_ACCOUNT CAT on CRD.CRD_ID=CAT.CAT_CRD_ID 
	  left join ACCOUNT ACN on CAT.CAT_ACN_ID=ACN.ACN_ID 
	  left join CARD_PRODUCT CPD on CRD.CRD_CPD_ID=CPD.CPD_ID 
	  left join CBC_TRAN_CODE CTR on TXN.TRL_TSC_CODE=CTR.CTR_CODE and TXNC.TRL_ORIGIN_CHANNEL=CTR.CTR_CHANNEL 
	where 
	  CPD.CPD_CODE in (''80'', ''81'', ''82'', ''83'') 
	  AND TXN.TRL_SYSTEM_TIMESTAMP < {Txn_End_Date}
	group by 
  	  BRC.BRC_CODE, BRC.BRC_NAME,TXNC.TRL_ORIGIN_CHANNEL,TXNC.TRL_IS_CORPORATE_CARD
	order by BRC.BRC_CODE, BRC.BRC_NAME,TXNC.TRL_ORIGIN_CHANNEL
	');
	
	update REPORT_DEFINITION set RED_BODY_QUERY = i_BODY_QUERY where RED_NAME = 'Cash Card Daily Transaction Summary';
	
END;
/