DECLARE

	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;

BEGIN 
	  
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'Beep Transactions', 'For Beep transactions','master','system',CURRENT_TIMESTAMP);
	
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'InstaPay Transactions', 'For Instapay Transactions','master','system',CURRENT_TIMESTAMP);
	
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'Pay to Mobile Transactions', 'For Pay to Mobile Transactions','master','system',CURRENT_TIMESTAMP);
	
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'Pesonet Transactions', 'For Pesonet Transactions','master','system',CURRENT_TIMESTAMP);
	
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'Recycler Transactions', 'For Recycler Transactions','master','system',CURRENT_TIMESTAMP);
	
	INSERT INTO REPORT_CATEGORY (REC_ID,REC_NAME,REC_DESCRIPTION,REC_BRANCH_FLAG,CREATED_BY,CREATED_DATE)
	VALUES ((SELECT MAX(REC_ID)+1 FROM REPORT_CATEGORY), 'RFID Transactions', 'For RFID Transactions','master','system',CURRENT_TIMESTAMP);
	
	UPDATE REPORT_CATEGORY SET REC_NAME = 'Extract Files' WHERE REC_NAME = 'BARTS Files';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'InstaPay Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME LIKE '%InstaPay%';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Beep Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME LIKE '%Beep%';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'RFID Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME LIKE '%RFID%';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Pesonet Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME LIKE '%Pesonet%';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Recycler Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME LIKE '%Recycler%';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Pay to Mobile Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME = 'List of Moving Cash Transactions';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Pay to Mobile Transactions')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME = 'ATM List of Cardless Withdrawal';
	
	UPDATE REPORT_DEFINITION SET RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'Extract Files')
	WHERE RED_REC_ID = (SELECT REC_ID FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports') AND RED_NAME = 'Finacle 360';
	
	DELETE FROM REPORT_CATEGORY WHERE REC_NAME = 'New Transactions Reports';

END;
/