DECLARE

	i_BODY_QUERY CLOB;

BEGIN 

	i_BODY_QUERY := TO_CLOB('SELECT
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
      "BANK CODE",
      SUM("APPROVED TRAN COUNT") "APPROVED TRAN COUNT",
      SUM("REJECTED TRAN COUNT") "REJECTED TRAN COUNT",
      COUNT("TOTAL TRAN COUNT") "TOTAL TRAN COUNT",
      0 "SHORT DISPENSE COUNT",
      0 "NO DISPENSE COUNT",
      0 "OVER DISPENSE COUNT",
      0 "HARDWARE FAILURE COUNT",
      SUM("CASH DISPENSED") "CASH DISPENSED",
      SUM("DEPOSITS") "DEPOSITS",
      SUM("BILL PAYMENTS") "BILL PAYMENTS",
      SUM("TRANSFERS") "TRANSFERS"
FROM (
SELECT
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, -4) "TERMINAL",
      CASE WHEN CBA.CBA_MNEM IS NOT NULL THEN CBA.CBA_MNEM ELSE '''' END AS "BANK MNEM",
      CASE 
	    WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_POST_COMPLETION_CODE = ''R'' AND TXN.TRL_TSC_CODE IN (SELECT CTR_CODE FROM CBC_TRAN_CODE WHERE CTR_CHANNEL = ''BNT'')
	        THEN (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT in (''DEBIT'', ''CREDIT'') AND ROWNUM=1)
	    WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_POST_COMPLETION_CODE IS NULL AND TXN.TRL_TSC_CODE IN (SELECT CTR_CODE FROM CBC_TRAN_CODE WHERE CTR_CHANNEL = ''BNT'')
	        THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT in (''DEBIT'', ''CREDIT'') AND ROWNUM=1)
	    WHEN TXN.TRL_ISS_NAME IS NOT NULL AND TXN.TRL_POST_COMPLETION_CODE = ''R'' 
	        THEN CTR.CTR_REV_MNEM 
		ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
      CASE WHEN CBA.CBA_CODE IS NOT NULL THEN LPAD(CBA.CBA_CODE, 4, 0) ELSE '''' END AS "BANK CODE",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 ELSE 0 END AS "APPROVED TRAN COUNT",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE != 0 THEN 1 ELSE 0 END AS "REJECTED TRAN COUNT",
      TXN.TRL_ID "TOTAL TRAN COUNT",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (1, 128) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "CASH DISPENSED",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (21, 26) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "DEPOSITS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE = 50 THEN TXN.TRL_AMT_TXN ELSE 0 END AS "BILL PAYMENTS",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 AND TXN.TRL_TSC_CODE IN (40, 42, 43, 44, 45, 52) THEN TXN.TRL_AMT_TXN ELSE 0 END AS "TRANSFERS"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
	  LEFT JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
	  
WHERE
      TXN.TRL_TSC_CODE IN (1, 128, 21, 26, 31, 40, 42, 43, 44, 45, 50, 52)
      AND TXN.TRL_TQU_ID = ''F''
      AND CTR.CTR_DEBIT_CREDIT = ''DEBIT''
      AND {Txn_Date}
)
GROUP BY
      "DATE",
      "TERMINAL",
      "BANK MNEM",
      "TRAN MNEM",
      "BANK CODE"
ORDER BY
      "TRAN MNEM" ASC,
      "TERMINAL" ASC,
      "BANK CODE" ASC');
	  
	  UPDATE REPORT_DEFINITION SET RED_BODY_QUERY = i_BODY_QUERY WHERE RED_NAME = 'Transaction Count Report';
	  
	  
	  i_BODY_QUERY := TO_CLOB('SELECT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      ABR.ABR_CODE "BRANCH CODE",
      ABR.ABR_NAME "BRANCH NAME",
      SUBSTR(AST.AST_TERMINAL_ID, -4) "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      TXN.TRL_DEST_STAN "SEQ NUMBER",
      SUBSTR(TXN.TRL_RRN, 9, 4) "TRACE NUMBER",
      TXN.TRL_PAN "ATM CARD NUMBER",
      TXN.TRL_PAN_EKY_ID,
      LPAD(CBA.CBA_CODE, 4, ''0'') "BANK CODE",
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      TXN.TRL_DATETIME_LOCAL_TXN "TIME",
      CASE 
	    WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_POST_COMPLETION_CODE = ''R'' AND TXN.TRL_TSC_CODE IN (SELECT CTR_CODE FROM CBC_TRAN_CODE WHERE CTR_CHANNEL = ''BNT'')
	        THEN (SELECT CTR_REV_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT in (''DEBIT'', ''CREDIT'') AND ROWNUM=1)
	    WHEN TXN.TRL_ISS_NAME IS NULL AND TXN.TRL_POST_COMPLETION_CODE IS NULL AND TXN.TRL_TSC_CODE IN (SELECT CTR_CODE FROM CBC_TRAN_CODE WHERE CTR_CHANNEL = ''BNT'')
	        THEN (SELECT CTR_MNEM FROM CBC_TRAN_CODE WHERE CTR_CODE=TXN.TRL_TSC_CODE AND CTR_CHANNEL=''BNT'' AND CTR_DEBIT_CREDIT in (''DEBIT'', ''CREDIT'') AND ROWNUM=1)
	    WHEN TXN.TRL_ISS_NAME IS NOT NULL AND TXN.TRL_POST_COMPLETION_CODE = ''R'' 
	        THEN CTR.CTR_REV_MNEM 
		ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
      CASE WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 10 THEN ''SA'' WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 20 THEN ''CA'' ELSE '''' END AS "FROM ACC TYPE",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      CASE WHEN TXN.TRL_ACCOUNT_TYPE_2_ATP_ID = 10 THEN ''SA'' WHEN TXN.TRL_ACCOUNT_TYPE_2_ATP_ID = 20 THEN ''CA'' ELSE '''' END AS "TO ACC TYPE",
      TXN.TRL_ACCOUNT_2_ACN_ID "TO ACCOUNT NO",
      TXN.TRL_ACCOUNT_2_ACN_ID_EKY_ID,
      TXN.TRL_AMT_TXN "AMOUNT",
      TXN.TRL_ACTION_RESPONSE_CODE "VOID CODE",
      ARC.ARC_NAME "COMMENT"
	FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      LEFT JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      LEFT JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
      JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
      JOIN ATM_BRANCHES ABR ON AST.AST_ABR_ID = ABR.ABR_ID
	WHERE
      TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_MCC_ID = 6011
      AND TXN.TRL_DEO_NAME IN (''CBC'',''CBS'')
      AND {Branch_Code}
      AND {Terminal}
      AND {Txn_Date}
	ORDER BY
      ABR.ABR_CODE ASC,
      AST.AST_TERMINAL_ID ASC,
      TXN.TRL_SYSTEM_TIMESTAMP ASC,
      TXN.TRL_DEST_STAN ASC,
      TXN.TRL_RRN ASC');
	  
	  UPDATE REPORT_DEFINITION SET RED_BODY_QUERY = i_BODY_QUERY WHERE RED_NAME = 'ATM Transaction List (On-Us/Acquirer)';
	  
	  i_BODY_QUERY := TO_CLOB('SELECT
      TXN.TRL_TQU_ID "TXN QUALIFIER",
      CBA.CBA_NAME "BANK NAME",
      CONCAT(LPAD(CBA.CBA_CODE, 4, ''0''),  TXN.TRL_CARD_ACPT_TERMINAL_IDENT) "ATM CODE",
      CBA.CBA_MNEM "BANK MNEM",
      TXN.TRL_DEST_STAN "SEQ NUMBER",
      SUBSTR(TXN.TRL_RRN, 9, 4) "TRACE NUMBER",
      TXN.TRL_PAN "ATM CARD NUMBER",
      TXN.TRL_PAN_EKY_ID,
      LPAD(CBA.CBA_CODE, 4, ''0'') "BANK CODE",
      TXN.TRL_DATETIME_LOCAL_TXN "DATE",
      TXN.TRL_DATETIME_LOCAL_TXN "TIME",
      CASE WHEN TXN.TRL_TQU_ID = ''R'' THEN CTR.CTR_REV_MNEM ELSE CTR.CTR_MNEM END AS "TRAN MNEM",
      CASE WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 10 THEN ''SA'' WHEN TXN.TRL_ACCOUNT_TYPE_1_ATP_ID = 20 THEN ''CA'' ELSE '' END AS "FROM ACC TYPE",
      TXN.TRL_ACCOUNT_1_ACN_ID "FROM ACCOUNT NO",
      TXN.TRL_ACCOUNT_1_ACN_ID_EKY_ID,
      CASE WHEN TXN.TRL_ACCOUNT_TYPE_2_ATP_ID = 10 THEN ''SA'' WHEN TXN.TRL_ACCOUNT_TYPE_2_ATP_ID = 20 THEN ''CA'' ELSE '' END AS "TO ACC TYPE",
      TXN.TRL_ACCOUNT_2_ACN_ID "TO ACCOUNT NO",
      TXN.TRL_ACCOUNT_2_ACN_ID_EKY_ID,
      TXN.TRL_AMT_TXN "AMOUNT",
      TXN.TRL_ACTION_RESPONSE_CODE "VOID CODE",
      ARC.ARC_NAME "COMMENT"
	FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_TRAN_CODE CTR ON TXN.TRL_TSC_CODE = CTR.CTR_CODE AND TXNC.TRL_ORIGIN_CHANNEL = CTR.CTR_CHANNEL
      JOIN CBC_BANK CBA ON LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = LPAD(CBA.CBA_CODE, 10, ''0'')
      JOIN AUTH_RESULT_CODE ARC ON TXN.TRL_ACTION_RESPONSE_CODE = ARC.ARC_CODE
	WHERE
      TXN.TRL_TQU_ID = ''F''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND TXN.TRL_DEO_NAME IS NULL
      AND TXN.TRL_MCC_ID=6011
      AND TXN.TRL_ISS_NAME IN (''CBC'',''CBS'')
      AND {Bank_Code}
      AND {Txn_Date}
	ORDER BY
      CBA.CBA_NAME ASC,
      TXN.TRL_SYSTEM_TIMESTAMP ASC,
      TXN.TRL_DEST_STAN ASC,
      TXN.TRL_RRN ASC');
	  
	  UPDATE REPORT_DEFINITION SET RED_BODY_QUERY = i_BODY_QUERY WHERE RED_NAME = 'ATM Transaction List (Issuer)';
	  
END;
/