DECLARE

	i_BODY_QUERY CLOB;
	i_BODY_FIELD CLOB;

BEGIN 
	  
	  i_BODY_QUERY := TO_CLOB('
SELECT
      COUNT("REJECTED COUNT") "REJECTED COUNT",
      COUNT("APPROVED COUNT") "APPROVED COUNT",
      COUNT("REJECTED COUNT") + COUNT("APPROVED COUNT") "TOTAL COUNT",
      SUM("AMOUNT") "AMOUNT"
FROM(
SELECT
      AST.AST_TERMINAL_ID "Terminal",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE != 0 THEN 1 END AS "REJECTED COUNT",
      CASE WHEN TXN.TRL_ACTION_RESPONSE_CODE = 0 THEN 1 END AS "APPROVED COUNT",
      TXN.TRL_AMT_TXN "AMOUNT"
FROM
      TRANSACTION_LOG TXN
      JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
WHERE
      TXN.TRL_TQU_ID = ''F'' 
	  AND NVL(TXN.TRL_POST_COMPLETION_CODE, '' '') != ''R''
      AND {Txn_Time}
	  AND {Terminal}
)
GROUP BY
      "Terminal"
ORDER BY
      "Terminal" ASC		
');

		i_BODY_FIELD := TO_CLOB('');
	  
	  
	  UPDATE REPORT_DEFINITION SET RED_BODY_QUERY = i_BODY_QUERY , RED_BODY_FIELDS = i_BODY_FIELD WHERE RED_NAME = 'ATM Daily Transaction Summary';
	  

END;
/