CREATE TABLE LOAD_USER 
   (	
    LOGIN_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    EMAIL VARCHAR2(100 BYTE) NOT NULL ENABLE,
    FIRST_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    LAST_NAME VARCHAR2(50 BYTE),
    BRANCH_CODE VARCHAR2(10 BYTE),
    ROLE_NAME VARCHAR2(50 BYTE) NOT NULL,
    INSTITUTION_CODE VARCHAR2(5 BYTE) NOT NULL,
	CONSTRAINT LOAD_USER_PK PRIMARY KEY ("LOGIN_NAME")
  ) TABLESPACE AUTH_REPORT_DATA_TS;
