package my.com.mandrill.base.config.audit;

public enum AuditActionType {

	INSTITUTION_CREATE,
	INSTITUTION_UPDATE,
	INSTITUTION_DELETE,
	REPORT_CATEGORY_CREATE,
	REPORT_CATEGORY_UPDATE,
	REPORT_CATEGORY_DELETE,
	REPORT_DEFINITION_CREATE,
	REPORT_DEFINITION_UPDATE,
	REPORT_DEFINITION_DELETE,
	REPORT_DELETE,
	REPORT_DOWNLOAD,
	REPORT_GENERATE,	
	ROLE_CREATE,
	ROLE_UPDATE,
	ROLE_DELETE,
	SYNCHRONIZE_DATABASE,
	SYSTEM_CONFIGURATION_CREATE,
	SYSTEM_CONFIGURATION_UPDATE,
	SYSTEM_CONFIGURATION_DELETE,
	SYNC_SCHEDULER_UDPATE,
	USER_CREATE,
	USER_UPDATE,
	USER_DELETE,
}
