-- Tracking				Date			Name	Description
-- Revise report		25-JULY-2021	WY		Revise IE reports based on spec

DECLARE
	i_BODY_QUERY CLOB;
	i_TRAILER_QUERY CLOB;
	
	
BEGIN 

	i_BODY_QUERY := TO_CLOB('SELECT
     BRC.BRC_CODE "BRANCH CODE",
     BRC.BRC_NAME "BRANCH NAME",
     COUNT(TXN.TRL_ID) "TOTAL COUNT",
     COUNT(TXN.TRL_ID) * 7.50 "TOTAL EXPENSE"
FROM
     TRANSACTION_LOG TXN
     JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
     JOIN BRANCH BRC ON CRD.CRD_CUSTOM_DATA = BRC.BRC_CODE
WHERE
      (TXN.TRL_TSC_CODE IN (128) OR (TXN.TRL_TSC_CODE = 1 AND TXN.TRL_FRD_REV_INST_ID IS NULL))
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = ''0''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXN.TRL_ISS_NAME = {V_Iss_Name}
	  AND (TXN.TRL_DEO_NAME = {V_IE_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_IE_Acqr_Inst_Id})
      AND {Txn_Date}
GROUP BY
      BRC.BRC_CODE,
      BRC.BRC_NAME
ORDER BY
      "BRANCH CODE" ASC
	');	
	
	i_TRAILER_QUERY := TO_CLOB('SELECT
     COUNT(TXN.TRL_ID) "TOTAL COUNT",
     COUNT(TXN.TRL_ID) * 7.50 "TOTAL EXPENSE"
FROM
     TRANSACTION_LOG TXN
     JOIN CARD CRD ON TXN.TRL_PAN = CRD.CRD_PAN
     JOIN BRANCH BRC ON CRD.CRD_CUSTOM_DATA = BRC.BRC_CODE
WHERE
      (TXN.TRL_TSC_CODE IN (128) OR (TXN.TRL_TSC_CODE = 1 AND TXN.TRL_FRD_REV_INST_ID IS NULL))
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = ''0''
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXN.TRL_ISS_NAME = {V_Iss_Name}
	  AND (TXN.TRL_DEO_NAME = {V_IE_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_IE_Acqr_Inst_Id})
      AND {Txn_Date}
	');
	
	UPDATE REPORT_DEFINITION SET 
		RED_BODY_QUERY = i_BODY_QUERY,
		RED_TRAILER_QUERY = i_TRAILER_QUERY
	WHERE RED_NAME = 'Inter-Entity Issuer ATM Withdrawal Expense';
	
END;
/