-- Tracking				Date			Name	Description
-- Revise report		12-AUG-2021		WY		Original script
-- JIRA 937				11-NOV-2021		WY		Fix format of Overall total section

DECLARE

	i_REPORT_NAME VARCHAR2(100) := 'Inter-Entity IBFT Transaction Fees';
	i_PROCESSING_CLASS_NAME VARCHAR2(100) := 'my.com.mandrill.base.reporting.billingAllocationReportsInterEntity.InterEntityIbftTransactionFees';
	i_BODY_QUERY CLOB;
	
BEGIN 

	i_BODY_QUERY := TO_CLOB('SELECT
  "BRANCH CODE",
  "BRANCH NAME",
  COUNT("TRANSMITTING ID") "TRANSMITTING COUNT",
  COUNT("TRANSMITTING ID")  * 5.00 AS "TRANSMITTING EXPENSE",
  COUNT("ACQUIRER ID") AS "ACQUIRER COUNT",
  COUNT("ACQUIRER ID") * 5.00 AS "ACQUIRER INCOME",
  COUNT("RECEIVING ID") AS "RECEIVING COUNT",
  COUNT("RECEIVING ID") * 5.00 AS "RECEIVING INCOME",
  ((COUNT("ACQUIRER ID")  +  COUNT("RECEIVING ID")) - COUNT("TRANSMITTING ID")) * 5.00 AS "TOTAL BILLING"
FROM (
SELECT
  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) "BRANCH CODE",
  ABR.ABR_NAME "BRANCH NAME",
  TXN.TRL_ID AS "TRANSMITTING ID",
  NULL AS "ACQUIRER ID",
  NULL AS "RECEIVING ID"     		
FROM
  TRANSACTION_LOG TXN
  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
  LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
  LEFT JOIN ATM_BRANCHES ABR ON ABR_ID = (SELECT MIN(ABR_ID) FROM ATM_BRANCHES WHERE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) = ABR_CODE)
  WHERE TXN.TRL_TSC_CODE IN (40, 42, 48)
  AND TXN.TRL_TQU_ID = ''F''
  AND TXN.TRL_ACTION_RESPONSE_CODE = 0
  AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
  AND TXN.TRL_ISS_NAME = {V_Iss_Name}
  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
  AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_IE_Recv_Inst_Id}
  AND {Txn_Date}
UNION
SELECT
  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) "BRANCH CODE",
  ABR.ABR_NAME "BRANCH NAME",
  TXN.TRL_ID AS "TRANSMITTING ID",
  NULL AS "ACQUIRER ID",
  NULL AS "RECEIVING ID" 
FROM
  TRANSACTION_LOG TXN
  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
  LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
  LEFT JOIN ATM_BRANCHES ABR ON ABR_ID = (SELECT MIN(ABR_ID) FROM ATM_BRANCHES WHERE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) = ABR_CODE)
  WHERE TXN.TRL_TSC_CODE IN (40, 42, 48)
  AND TXN.TRL_TQU_ID = ''F''
  AND TXN.TRL_ACTION_RESPONSE_CODE = 0
  AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
  AND TXN.TRL_ISS_NAME = {V_Iss_Name}
  AND (TXN.TRL_DEO_NAME = {V_IE_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_IE_Acqr_Inst_Id})
  AND (LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') IN ({V_Recv_Inst_Id},{V_IE_Recv_Inst_Id}) OR (TXN.TRL_FRD_REV_INST_ID IS NULL AND TXN.TRL_TSC_CODE = 40))
  AND {Txn_Date}
UNION  
SELECT
  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) "BRANCH CODE",
  ABR.ABR_NAME "BRANCH NAME",
  NULL AS "TRANSMITTING ID",
  TXN.TRL_ID "ACQUIRER ID",
  NULL AS "RECEIVING ID"
FROM
  TRANSACTION_LOG TXN
  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
  LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
  LEFT JOIN ATM_BRANCHES ABR ON ABR_ID = (SELECT MIN(ABR_ID) FROM ATM_BRANCHES WHERE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) = ABR_CODE)
  WHERE (TXN.TRL_TSC_CODE IN (42, 44, 48) OR (TXN.TRL_TSC_CODE = 40 AND TXN.TRL_ISS_NAME <> {V_Iss_Name}))
  AND TXN.TRL_TQU_ID = ''F''
  AND TXN.TRL_ACTION_RESPONSE_CODE = 0
  AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
  AND (TXN.TRL_DEO_NAME = {V_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_Acqr_Inst_Id})
  AND (TXN.TRL_ISS_NAME = {V_IE_Iss_Name} OR (TXN.TRL_ISS_NAME = {V_Iss_Name} AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') <> {V_Recv_Inst_Id}))
  AND {Txn_Date}
UNION  
SELECT
  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) "BRANCH CODE",
  ABR.ABR_NAME "BRANCH NAME",
  NULL AS "TRANSMITTING ID",
  NULL AS "ACQUIRER ID",
  TXN.TRL_ID "RECEIVING ID"     		
FROM
  TRANSACTION_LOG TXN
  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
  LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
  LEFT JOIN ATM_BRANCHES ABR ON ABR_ID = (SELECT MIN(ABR_ID) FROM ATM_BRANCHES WHERE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) = ABR_CODE)
  WHERE TXN.TRL_TSC_CODE IN (40, 42, 44, 48)
  AND TXN.TRL_TQU_ID = ''F''
  AND TXN.TRL_ACTION_RESPONSE_CODE = 0
  AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
  AND (LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_Recv_Inst_Id} OR (TXN.TRL_FRD_REV_INST_ID IS NULL AND TXN.TRL_TSC_CODE = 40))
  AND TXN.TRL_ISS_NAME = {V_Iss_Name}
  AND (TXN.TRL_DEO_NAME = {V_IE_Deo_Name} OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') = {V_IE_Acqr_Inst_Id})
  AND {Txn_Date}
UNION
SELECT
  SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) "BRANCH CODE",
  ABR.ABR_NAME "BRANCH NAME",
  NULL AS "TRANSMITTING ID",
  NULL AS "ACQUIRER ID",
  TXN.TRL_ID "RECEIVING ID"     		
FROM
  TRANSACTION_LOG TXN
  JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
  LEFT JOIN ATM_STATIONS AST ON TXN.TRL_CARD_ACPT_TERMINAL_IDENT = AST.AST_TERMINAL_ID
  LEFT JOIN ATM_BRANCHES ABR ON ABR_ID = (SELECT MIN(ABR_ID) FROM ATM_BRANCHES WHERE SUBSTR(TXN.TRL_CARD_ACPT_TERMINAL_IDENT, 1, 4) = ABR_CODE)
  WHERE TXN.TRL_TSC_CODE IN (40, 42, 44, 48)
  AND TXN.TRL_TQU_ID = ''F''
  AND TXN.TRL_ACTION_RESPONSE_CODE = 0
  AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
  AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_Recv_Inst_Id}
  AND TXN.TRL_ISS_NAME = {V_IE_Iss_Name}
  AND (TXN.TRL_DEO_NAME IN ({V_IE_Deo_Name},{V_Deo_Name}) OR LPAD(TXN.TRL_ACQR_INST_ID, 10, ''0'') IN ({V_IE_Acqr_Inst_Id},{V_Acqr_Inst_Id}))
  AND {Txn_Date})  
GROUP BY "BRANCH CODE", "BRANCH NAME"
ORDER BY "BRANCH CODE"');	
	
	
	UPDATE REPORT_DEFINITION SET 
		RED_BODY_QUERY = i_BODY_QUERY,
		RED_PROCESSING_CLASS = i_PROCESSING_CLASS_NAME
	WHERE RED_NAME = i_REPORT_NAME;
	
	update report_definition set red_header_fields = REPLACE(red_header_fields, 'CHINA BANKING CORPORATION', 'CHINA BANK SAVINGS') WHERE RED_NAME = i_REPORT_NAME AND red_ins_id = 2;
	
END;
/