version: '2'
services:
    base-app:
        image: base
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://base-mariadb:3306/base
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=base-elasticsearch:9300
        ports:
            - 8080:8080
    base-mariadb:
        extends:
            file: mariadb.yml
            service: base-mariadb
    base-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: base-elasticsearch
