//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 06:20:25 PM SGT 
//


package com.authentic.activemq.jndi.activemqresources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="secure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="securityModule" type="{http://www.jndi.activemq.authentic.com/ActiveMQResources}SecurityModule"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secure",
    "securityModule"
})
@XmlRootElement(name = "ActiveMQResources")
public class ActiveMQResources {

    protected boolean secure;
    @XmlElement(required = true)
    protected SecurityModule securityModule;

    /**
     * Gets the value of the secure property.
     * 
     */
    public boolean isSecure() {
        return secure;
    }

    /**
     * Sets the value of the secure property.
     * 
     */
    public void setSecure(boolean value) {
        this.secure = value;
    }

    /**
     * Gets the value of the securityModule property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityModule }
     *     
     */
    public SecurityModule getSecurityModule() {
        return securityModule;
    }

    /**
     * Sets the value of the securityModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityModule }
     *     
     */
    public void setSecurityModule(SecurityModule value) {
        this.securityModule = value;
    }

}
