export * from '../../entities/user-extra/user-extra.model';
export * from './user-extra-popup.service';
export * from './user-extra.service';
export * from './user-extra-edit-dialog.component';
export * from './user-extra-new-dialog.component';
export * from './user-extra-delete-dialog.component';
export * from './user-extra-detail.component';
export * from './user-extra.component';
export * from './user-extra.route';
