Insert into CBC_GL_ENTRY (GLE_ID,GLE_GLT_ID,GLE_MAIN_DIRECTION,GLE_TRAN_CHANNEL,GLE_TRAN_TYPE,GLE_CARD_TYPE,GLE_FROM_ACCOUNT_TYPE,GLE_TO_ACCOUNT_TYPE,GLE_TRAN_CODE_EXCLUDE,GLE_BP_SETTLEMENT,GLE_BP_INCLUDE,GLE_BP_EXEMPT,GLE_DEBIT_ACCOUNT,GLE_DEBIT_DESCRIPTION,GLE_CREDIT_ACCOUNT,GLE_CREDIT_DESCRIPTION,GLE_SVC_ENABLED,GLE_SVC_AUTHENTIC,GLE_SVC_AMT,GLE_ENTRY_ENABLED,GLE_ENTRY_SEPARATE,GLE_CREATED_TS,GLE_LAST_UPDATE_TS) 
values (CBC_GL_ENTRY_SEQUENCE.nextVal,9,'RECEIVING','EBK',21,'Default','00','00',null,null,null,null,'Accts. Payable - E-Banking','CASH CARD CMS ACA LOADING','Accts. Payable - Cash Card','CASH CARD CMS ACA LOADING',null,null,null,'Y','N',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO CBC_GL_ACCOUNT (GLA_ID,GLA_NAME,GLA_NUMBER,GLA_LAST_UPDATE_TS,GLA_INSTITUTION) 
VALUES (CBC_GL_ACCOUNT_SEQUENCE.nextVal, 'Accts. Payable - E-Banking', '50090024501050', current_timestamp, 'CBC');

COMMIT;