Insert into CBC_GL_ACCOUNT (GLA_ID,GLA_NAME,GLA_NUMBER,GLA_LAST_UPDATE_TS,GLA_INSTITUTION) values 
(CBC_GL_ACCOUNT_SEQUENCE.nextVal,'Accts. Receivable - Bancnet IBFT','80010012221007',CURRENT_TIMESTAMP,'CBS');

COMMIT;