UPDATE CBC_GL_ACCOUNT SET GLA_NUMBER = '50080024537011', GLA_LAST_UPDATE_TS = current_timestamp WHERE GLA_NAME = 'Accts. Payable - Bancnet Instapay' AND GLA_INSTITUTION = 'CBC';

INSERT INTO CBC_GL_ACCOUNT (GLA_ID,GLA_NAME,GLA_NUMBER,GLA_LAST_UPDATE_TS,GLA_INSTITUTION) VALUES (CBC_GL_ACCOUNT_SEQUENCE.nextVal, 'Accts. Receivable - BancNet Instapay', '50080012221151', current_timestamp, 'CBC');
	
update CBC_GL_ENTRY set GLE_DEBIT_ACCOUNT='Accts. Receivable - BancNet Instapay' where GLE_TRAN_CHANNEL='PGW' and GLE_GLT_ID=9;


COMMIT;