
INSERT INTO CBC_GL_ENTRY (GLE_ID, GLE_GLT_ID,GLE_MAIN_DIRECTION,GLE_TRAN_CHANNEL,GLE_TRAN_TYPE,GLE_CARD_TYPE,GLE_FROM_ACCOUNT_TYPE,GLE_TO_ACCOUNT_TYPE,	GLE_TRAN_CODE_EXCLUDE,GLE_BP_SETTLEMENT,GLE_BP_INCLUDE,GLE_BP_EXEMPT,GLE_DEBIT_ACCOUNT,GLE_DEBIT_DESCRIPTION,GLE_CREDIT_ACCOUNT,GLE_CREDIT_DESCRIPTION,
			GLE_SVC_ENABLED,GLE_SVC_AUTHENTIC,GLE_SVC_AMT,GLE_ENTRY_ENABLED,GLE_ENTRY_SEPARATE,GLE_CREATED_TS,GLE_LAST_UPDATE_TS) 
				VALUES (CBC_GL_ENTRY_SEQUENCE.nextVal, (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = 'CASH CARD'), 'ON-US', 'OTC', '1', 'Default', '00', '00',NULL, NULL, NULL, NULL, 'Cash Card Tran Clrg', 'Cash Card Loading', 'Accts. Payable - Cash Card', 'Cash Card Loading',NULL, NULL, NULL, 'Y', 'Y', current_timestamp, current_timestamp);

INSERT INTO CBC_GL_ENTRY (GLE_ID, GLE_GLT_ID,GLE_MAIN_DIRECTION,GLE_TRAN_CHANNEL,GLE_TRAN_TYPE,GLE_CARD_TYPE,GLE_FROM_ACCOUNT_TYPE,GLE_TO_ACCOUNT_TYPE,GLE_TRAN_CODE_EXCLUDE,GLE_BP_SETTLEMENT,GLE_BP_INCLUDE,GLE_BP_EXEMPT,GLE_DEBIT_ACCOUNT,GLE_DEBIT_DESCRIPTION,GLE_CREDIT_ACCOUNT,GLE_CREDIT_DESCRIPTION,
			GLE_SVC_ENABLED,GLE_SVC_AUTHENTIC,GLE_SVC_AMT,GLE_ENTRY_ENABLED,GLE_ENTRY_SEPARATE,GLE_CREATED_TS,GLE_LAST_UPDATE_TS) 
			VALUES (CBC_GL_ENTRY_SEQUENCE.nextVal, (SELECT GLT_ID FROM CBC_GL_TRANSACTION WHERE GLT_NAME = 'CASH CARD'), 'ON-US', 'OTC', '21', 'Default', '00', '00',	NULL, NULL, NULL, NULL, 'Cash Card Tran Clrg', 'Cash Card Loading', 'Accts. Payable - Cash Card', 'Cash Card Loading',NULL, NULL, NULL, 'Y', 'Y', current_timestamp, current_timestamp);
				
commit;