-- release-20210806
Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) values (CBC_TRAN_CODE_SEQUENCE.nextVal,31,'I-CDM','INQ','N/A','DEBIT',CURRENT_TIMESTAMP);
Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) values (CBC_TRAN_CODE_SEQUENCE.nextVal,31,'CDM','INQ','N/A','DEBIT',CURRENT_TIMESTAMP);

update CBC_TRAN_CODE set CTR_CHANNEL='I-CDM' where CTR_CHANNEL='CDM' and CTR_CODE=1 and CTR_MNEM='CWI';
update cbc_tran_code set ctr_channel = concat('I-',CTR_CHANNEL) where ctr_code=48;