-- RFID SVC GL
UPDATE CBC_GL_ACCOUNT SET GLA_NUMBER = '50080024537041', GLA_LAST_UPDATE_TS = current_timestamp WHERE GLA_NAME = 'Accts. Payable - RFID TFee' AND GLA_INSTITUTION = 'CBC';
UPDATE CBC_GL_ACCOUNT SET GLA_NUMBER = '80010024537041', GLA_LAST_UPDATE_TS = current_timestamp WHERE GLA_NAME = 'Accts. Payable - RFID TFee' AND GLA_INSTITUTION = 'CBS';


COMMIT;