-- Disable BIR entries for BP
update CBC_GL_ENTRY set GLE_ENTRY_ENABLED='N' where GLE_TRAN_TYPE=50 and GLE_TRAN_CHANNEL='ATM' and GLE_GLT_ID=(select GLT_ID from CBC_GL_TRANSACTION where GLT_CODE='BP') and GLE_DEBIT_DESCRIPTION='BIR REMITTANCE';


COMMIT;