-- Insert Cash Card Inter-Entity
Insert into CBC_GL_ENTRY (GLE_ID,GLE_GLT_ID,GLE_MAIN_DIRECTION,GLE_TRAN_CHANNEL,GLE_TRAN_TYPE,GLE_CARD_TYPE,GLE_FROM_ACCOUNT_TYPE,GLE_TO_ACCOUNT_TYPE,GLE_TRAN_CODE_EXCLUDE,GLE_BP_SETTLEMENT,GLE_BP_INCLUDE,GLE_BP_EXEMPT,GLE_DEBIT_ACCOUNT,GLE_DEBIT_DESCRIPTION,GLE_CREDIT_ACCOUNT,GLE_CREDIT_DESCRIPTION,GLE_SVC_ENABLED,GLE_SVC_AUTHENTIC,GLE_SVC_AMT,GLE_ENTRY_ENABLED,GLE_ENTRY_SEPARATE,GLE_CREATED_TS,GLE_LAST_UPDATE_TS) values (CBC_GL_ENTRY_SEQUENCE.nextVal,9,'ISSUER','BNT',0,'Default','10','20',null,null,null,null,'Accts. Payable - Cash Card - Reg','BANCNET POS TRANSACTIONS','Accts. Payable - Bancnet POS','BANCNET POS TRANSACTIONS',null,null,null,'Y','N',null,to_timestamp('30/05/2019 11:00:16.377000000','DD/MM/RRRR HH24:MI:SSXFF'));

update CBC_GL_ENTRY set GLE_DEBIT_DESCRIPTION='INSTAPAY TRANSFER CHARGE',GLE_CREDIT_DESCRIPTION='INSTAPAY TRANSFER CHARGE' where gle_glt_id=9 and gle_tran_type=46 and gle_svc_enabled='Y';
update CBC_GL_ENTRY set GLE_DEBIT_DESCRIPTION='PESONET TRANSFER CHARGE',GLE_CREDIT_DESCRIPTION='PESONET TRANSFER CHARGE' where gle_glt_id=9 and gle_tran_type=47 and gle_svc_enabled='Y';


commit;