INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'BANCNET BPS-POS'),777777,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'CUP'),621094,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),476114,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'MASTERCARD'),679997,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'MASTERCARD'),679999,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'BDO Gateway (Mastercard)'),545721,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),444444,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'MASTERCARD'),541333,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'CUP'),817199,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'CUP'),816399,CURRENT_TIMESTAMP);


INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),402524,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),412344,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),476126,CURRENT_TIMESTAMP);

INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS)
VALUES (CBC_BIN_SEQUENCE.nextVal,(SELECT CBA_ID FROM CBC_BANK WHERE CBA_NAME = 'VISA GATEWAY'),476134,CURRENT_TIMESTAMP);

COMMIT;