-- Disable BIR entries for BP
update CBC_GL_ENTRY set GLE_ENTRY_ENABLED='N' where GLE_DEBIT_DESCRIPTION='BIR REMITTANCE';
update CBC_GL_ENTRY set GLE_ENTRY_ENABLED='N' where GLE_DEBIT_DESCRIPTION='BANCNET EGOV - SSS';
update CBC_GL_ENTRY set GLE_ENTRY_ENABLED='N' where GLE_DEBIT_DESCRIPTION='BANCNET EGOV-PHILHEALTH';
update CBC_GL_ENTRY set GLE_ENTRY_ENABLED='N' where GLE_DEBIT_DESCRIPTION='BANCNET EGOV-PAG IBIG';

COMMIT;