Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-ATM','ACI','ARR','CREDIT',CURRENT_TIMESTAMP);

Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-IVR','TCI','TRR','CREDIT',CURRENT_TIMESTAMP);

Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-MBK','MCI','MRR','CREDIT',CURRENT_TIMESTAMP);

Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-CDM','CCI','CRR','CREDIT',CURRENT_TIMESTAMP);

Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-EBK','ECI','ERR','CREDIT',CURRENT_TIMESTAMP);

Insert into CBC_TRAN_CODE (CTR_ID,CTR_CODE,CTR_CHANNEL,CTR_MNEM,CTR_REV_MNEM,CTR_DEBIT_CREDIT,CTR_LAST_UPDATE_TS) 
values (CBC_TRAN_CODE_SEQUENCE.nextVal,21,'I-PGW','BZC','N/A','CREDIT',CURRENT_TIMESTAMP);


