INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS) VALUES (CBC_BIN_SEQUENCE.NEXTVAL, (SELECT CBA_ID FROM CBC_BANK WHERE CBA_CODE = '0728'), '999991', current_timestamp);
INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS) VALUES (CBC_BIN_SEQUENCE.NEXTVAL, (SELECT CBA_ID FROM CBC_BANK WHERE CBA_CODE = '0850'), '999992', current_timestamp);
INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS) VALUES (CBC_BIN_SEQUENCE.NEXTVAL, (SELECT CBA_ID FROM CBC_BANK WHERE CBA_CODE = '8885'), '999993', current_timestamp);
INSERT INTO CBC_BIN (CBI_ID, CBI_CBA_ID, CBI_BIN, CBI_LAST_UPDATE_TS) VALUES (CBC_BIN_SEQUENCE.NEXTVAL, (SELECT CBA_ID FROM CBC_BANK WHERE CBA_CODE = '8880'), '999994', current_timestamp);

commit;