update CBC_TRAN_CODE set CTR_MNEM='CCW',CTR_REV_MNEM='N/A',CTR_DEBIT_CREDIT='DEBIT' where CTR_CODE=1 and CTR_CHANNEL='OTC';
update CBC_TRAN_CODE set CTR_MNEM='CCS',CTR_REV_MNEM='N/A',CTR_DEBIT_CREDIT='CREDIT' where CTR_CODE=21 and CTR_CHANNEL='OTC';

commit;