INSERT INTO USER_EXTRA_ROLES (ROLES_ID, USER_EXTRAS_ID)
VALUES ((SELECT ID FROM ROLE_EXTRA WHERE NAME = 'operation'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbcoperator1'));

INSERT INTO USER_EXTRA_ROLES (ROLES_ID, USER_EXTRAS_ID)
VALUES ((SELECT ID FROM ROLE_EXTRA WHERE NAME = 'operation'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbcoperator2'));

INSERT INTO USER_EXTRA_ROLES (ROLES_ID, USER_EXTRAS_ID)
VALUES ((SELECT ID FROM ROLE_EXTRA WHERE NAME = 'operation'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbsoperator1'));

INSERT INTO USER_EXTRA_ROLES (ROLES_ID, USER_EXTRAS_ID)
VALUES ((SELECT ID FROM ROLE_EXTRA WHERE NAME = 'operation'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbsoperator2'));

INSERT INTO USER_EXTRA_INSTITUTIONS (INSTITUTIONS_ID,USER_EXTRAS_ID)
VALUES ((SELECT ID FROM INSTITUTION WHERE NAME = 'ChinaBank (CBC)'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbcoperator1'));

INSERT INTO USER_EXTRA_INSTITUTIONS (INSTITUTIONS_ID,USER_EXTRAS_ID)
VALUES ((SELECT ID FROM INSTITUTION WHERE NAME = 'ChinaBank (CBC)'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbcoperator2'));

INSERT INTO USER_EXTRA_INSTITUTIONS (INSTITUTIONS_ID,USER_EXTRAS_ID)
VALUES ((SELECT ID FROM INSTITUTION WHERE NAME = 'China Bank Savings (CBS)'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbsoperator1'));

INSERT INTO USER_EXTRA_INSTITUTIONS (INSTITUTIONS_ID,USER_EXTRAS_ID)
VALUES ((SELECT ID FROM INSTITUTION WHERE NAME = 'China Bank Savings (CBS)'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'cbsoperator2'));

INSERT INTO USER_EXTRA_ROLES (ROLES_ID, USER_EXTRAS_ID)
VALUES ((SELECT ID FROM ROLE_EXTRA WHERE NAME = 'operation'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'jetjvill'));

INSERT INTO USER_EXTRA_INSTITUTIONS (INSTITUTIONS_ID,USER_EXTRAS_ID)
VALUES ((SELECT ID FROM INSTITUTION WHERE NAME = 'ChinaBank (CBC)'),(SELECT ID FROM USER_EXTRA WHERE NAME = 'jetjvill'));

COMMIT;