SET DEFINE OFF;
ALTER SESSION SET CURRENT_SCHEMA = ATM5ADM;

UPDATE CBC_BILLER SET CBL_SETTLEMENT_TYPE = 'WOS' WHERE CBL_CODE = '907' AND CBL_MNEM = 'MCBL';
UPDATE CBC_BILLER SET CBL_SETTLEMENT_TYPE = 'AP' WHERE CBL_CODE = '132' AND CBL_MNEM = 'AUBC';
UPDATE CBC_BILLER SET CBL_SETTLEMENT_TYPE = 'AP' WHERE CBL_CODE = '026' AND CBL_MNEM = 'MBCD';

COMMIT;