-- Tracking				Date			Name	Description
-- Revise report		29-JULY-2021	WY		Revise report based on spec

DECLARE
    i_BODY_FIELDS CLOB;
    i_BODY_QUERY CLOB;
    i_TRAILER_QUERY CLOB;
    
BEGIN 
	
	i_BODY_QUERY := TO_CLOB('START ISSUING
SELECT
      (SELECT CBA_CODE FROM CBC_BANK WHERE LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = LPAD(CBA_CODE, 10, ''0'')) AS "BANK CODE",
      (SELECT CBA_NAME FROM CBC_BANK WHERE LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = LPAD(CBA_CODE, 10, ''0'')) AS "BANK NAME",
      COUNT(TXN.TRL_ID) "TRANSMITTING COUNT",
      SUM(TXN.TRL_AMT_TXN) "TRANSMITTING TOTAL",
      0 "RECEIVING COUNT",
      0 "RECEIVING TOTAL"
FROM
      TRANSACTION_LOG TXN
      join TRANSACTION_LOG_CUSTOM TXNC on TXN.TRL_ID=TXNC.TRL_ID
	  join BRANCH BRC on TXNC.TRL_CARD_BRANCH = BRC.BRC_CODE 
WHERE
      TXN.TRL_TSC_CODE IN (42, 44, 45, 48)
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXN.TRL_ISS_NAME = {V_Iss_Name}
      AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_IE_Recv_Inst_Id}
      AND {Bank_Code}
      AND {Txn_Date}
GROUP BY
      TXN.TRL_FRD_REV_INST_ID
ORDER BY
      "BANK NAME" ASC
END ISSUING
START RECEIVING
SELECT
      CBA.CBA_CODE "BANK CODE",
      CBA.CBA_NAME "BANK NAME",
      0 "TRANSMITTING COUNT",
      0 "TRANSMITTING TOTAL",
      COUNT(TXN.TRL_ID) "RECEIVING COUNT",
      SUM(TXN.TRL_AMT_TXN) "RECEIVING TOTAL"
FROM
      TRANSACTION_LOG TXN
      JOIN TRANSACTION_LOG_CUSTOM TXNC ON TXN.TRL_ID=TXNC.TRL_ID
      JOIN CBC_BIN CBI ON TXNC.TRL_CARD_BIN = CBI.CBI_BIN
      JOIN CBC_BANK CBA ON CBI.CBI_CBA_ID = CBA.CBA_ID
WHERE
      TXN.TRL_TSC_CODE IN (42, 44, 45, 48)
      AND TXN.TRL_TQU_ID = ''F''
      AND TXN.TRL_ACTION_RESPONSE_CODE = 0
      AND NVL(TXN.TRL_POST_COMPLETION_CODE, ''O'') != ''R''
      AND TXN.TRL_ISS_NAME = {V_IE_Iss_Name}
      AND LPAD(TXN.TRL_FRD_REV_INST_ID, 10, ''0'') = {V_Recv_Inst_Id}
      AND {Bank_Code}
      AND {Txn_Date}
GROUP BY
      CBA.CBA_CODE,
      CBA.CBA_NAME
ORDER BY
      "BANK NAME" ASC
END RECEIVING');
	
	
	UPDATE REPORT_DEFINITION set 
		RED_BODY_QUERY = i_BODY_QUERY
	where RED_NAME = 'Inter-Entity Summary of Approved IBFT Transactions Net Settlement';
	
	update report_definition set red_header_fields = REPLACE(red_header_fields, 'CHINA BANK CORPORATION', 'CHINA BANK SAVINGS') WHERE RED_NAME = 'Inter-Entity Summary of Approved IBFT Transactions Net Settlement' AND red_ins_id = 2;
	
	update report_definition set red_header_fields = REPLACE(red_header_fields, '0010', '0112') WHERE RED_NAME = 'Inter-Entity Summary of Approved IBFT Transactions Net Settlement' AND red_ins_id = 2;
	
END;
/