-- Alter to the correct schema
-- ALTER SESSION SET CURRENT_SCHEMA=A5SWUAT;

GRANT SELECT ON ACCOUNT TO ATM5RPT;
GRANT SELECT ON ACCOUNT_TYPE TO ATM5RPT;
GRANT SELECT ON ATM_SUMMARY_COUNTERS TO ATM5RPT;
GRANT SELECT ON ATM_SUMMARY_VALUES TO ATM5RPT;
GRANT SELECT ON AUTH_PROCESSING_PROFILE TO ATM5RPT;
GRANT SELECT ON BRANCH TO ATM5RPT;
GRANT SELECT ON CARD TO ATM5RPT;
GRANT SELECT ON CARD_ACCOUNT TO ATM5RPT;
GRANT SELECT ON CARD_PRODUCT TO ATM5RPT;
GRANT SELECT ON CUSTOMER TO ATM5RPT;
GRANT SELECT ON CBC_MOVING_CASH TO ATM5RPT;
GRANT SELECT ON CBC_BANK TO ATM5RPT;
GRANT SELECT ON CBC_BIN TO ATM5RPT;
GRANT SELECT ON CBC_BILLER TO ATM5RPT;
GRANT SELECT ON CBC_TRAN_CODE TO ATM5RPT;
GRANT SELECT ON CBC_GL_TRANSACTION TO ATM5RPT;
GRANT SELECT ON CBC_GL_ACCOUNT TO ATM5RPT;
GRANT SELECT ON CBC_GL_ENTRY TO ATM5RPT;
GRANT SELECT ON ATM_STATIONS TO ATM5RPT;
GRANT SELECT ON ATM_BRANCHES TO ATM5RPT;
GRANT SELECT ON ATM_STATUS TO ATM5RPT;
GRANT SELECT ON ATM_STATUS_HISTORY TO ATM5RPT;
GRANT SELECT ON ATM_DEVICE_STATUS TO ATM5RPT;
GRANT SELECT ON ATM_DEVICE_TOTALS TO ATM5RPT;
GRANT SELECT ON ATM_TXN_ACTIVITY_LOG TO ATM5RPT;
GRANT SELECT ON ATM_JOURNAL_LOG TO ATM5RPT;
GRANT SELECT ON AUTH_RESULT_CODE TO ATM5RPT;
GRANT SELECT ON ENCRYPTION_KEY TO ATM5RPT;
GRANT SELECT ON SECURE_KEY TO ATM5RPT;
GRANT SELECT ON SECURITY_PARAMETERS TO ATM5RPT;
GRANT SELECT ON TRANSACTION_CODE TO ATM5RPT;
GRANT SELECT ON TRANSACTION_LOG TO ATM5RPT;
GRANT SELECT ON MERCHANT TO ATM5RPT;
GRANT SELECT ON TABLE_DETAILS TO ATM5RPT;
GRANT SELECT ON DEVICE_ESTATE_OWNER TO ATM5RPT;
GRANT SELECT ON ISSUER TO ATM5RPT;


