-- Tracking				Date			Name	Description
-- Revise Report	 	25-JULY-2021	WY		Revise report according to requirement

DECLARE
	
	i_BODY_QUERY CLOB;
	
BEGIN 
	
	i_BODY_QUERY := TO_CLOB('
SELECT
      AST.AST_ARE_NAME "REGION",
      AST.AST_TERMINAL_ID "TERMINAL",
      AST.AST_ALO_LOCATION_ID "LOCATION",
      AJL.AJL_TIMESTAMP "DATE TIME",
      AJL.AJL_EJ_DATA "EXCEPTION"
	FROM
      ATM_STATIONS AST
      JOIN ATM_JOURNAL_LOG AJL ON AST.AST_ID = AJL.AJL_AST_ID
	  JOIN DEVICE_ESTATE_OWNER DEO ON AST.AST_DEO_ID = DEO.DEO_ID
      AND {Txn_Date}
	WHERE (AJL.AJL_EJ_DATA LIKE ''%*U*%'' OR AJL.AJL_EJ_DATA LIKE ''%*S*%'' OR AJL.AJL_EJ_DATA LIKE ''%*2*%'')
	AND DEO.DEO_NAME = {V_Deo_Name}
	ORDER BY
      AST.AST_ARE_NAME ASC,
      AST.AST_TERMINAL_ID ASC,
      AJL.AJL_TIMESTAMP ASC');
	
	UPDATE REPORT_DEFINITION set 
		RED_BODY_QUERY = i_BODY_QUERY
	where RED_NAME = 'ATM Daily Exception Messages';
	
END;
/